import sqlite3
import os

db_path = os.path.join(os.path.dirname(__file__), 'app', 'src', 'main', 'assets', 'si.db')

os.makedirs(os.path.dirname(db_path), exist_ok=True)

if os.path.exists(db_path):
    os.remove(db_path)

conn = sqlite3.connect(db_path)
cursor = conn.cursor()

sql_script = """
--==============================================================
-- Adaptado para SQLite (2026)
--==============================================================

-- Deshabilitar llaves foráneas temporalmente para poder borrar tablas en cualquier orden
PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS CATEGORIA_HABILIDAD;
DROP TABLE IF EXISTS GENERO;
DROP TABLE IF EXISTS TIPO_DOCUMENTO;
DROP TABLE IF EXISTS DEPARTAMENTO;
DROP TABLE IF EXISTS MUNICIPIO;
DROP TABLE IF EXISTS DISTRITO;
DROP TABLE IF EXISTS INSTITUCION;
DROP TABLE IF EXISTS GRADO_ACADEMICO;
DROP TABLE IF EXISTS EMPRESA;
DROP TABLE IF EXISTS POSTULANTE;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS CERTIFICACION;
DROP TABLE IF EXISTS OFERTA_TRABAJO;
DROP TABLE IF EXISTS DETALLE_REQUISITO;
DROP TABLE IF EXISTS EXPERIENCIA_LABORAL;
DROP TABLE IF EXISTS OFERTA_ACADEMICA;
DROP TABLE IF EXISTS FORMACION_ACADEMICA;
DROP TABLE IF EXISTS HABILIDAD;
DROP TABLE IF EXISTS HABILIDAD_POSTULANTE;
DROP TABLE IF EXISTS POSTULACION;
DROP TABLE IF EXISTS RED_SOCIAL;
DROP TABLE IF EXISTS RED_SOCIAL_POSTULANTE;

PRAGMA foreign_keys = ON;

--==============================================================
-- Tablas Maestras (Nivel 0)
--==============================================================

CREATE TABLE CATEGORIA_HABILIDAD (
    ID_CATEGORIA_HABILIDAD INTEGER PRIMARY KEY NOT NULL,
    NOMBRE_CATEGORIA       VARCHAR(50)
);

CREATE TABLE GENERO (
    ID_GENERO       INTEGER PRIMARY KEY NOT NULL,
    NOMBRE_GENERO   VARCHAR(20)
);

CREATE TABLE TIPO_DOCUMENTO (
    ID_TIPO_DOCUMENTO INTEGER PRIMARY KEY NOT NULL,
    NOMBRE_TIPO       VARCHAR(25)
);

CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO      INTEGER PRIMARY KEY NOT NULL,
    NOMBRE_DEPARTAMENTO  VARCHAR(50)
);

CREATE TABLE INSTITUCION (
    ID_INSTITUCION      INTEGER PRIMARY KEY NOT NULL,
    NOMBRE_INSTITUCION  VARCHAR(150)
);

CREATE TABLE GRADO_ACADEMICO (
    ID_GRADO_ACADEMICO INTEGER PRIMARY KEY NOT NULL,
    NOMBRE_GRADO        VARCHAR(50)
);

CREATE TABLE RED_SOCIAL (
    ID_RED_SOCIAL INTEGER PRIMARY KEY NOT NULL,
    NOMBRE_RED    VARCHAR(50),
    LOGO_ICONO    VARCHAR(50)
);

--==============================================================
-- Tablas con Dependencias (Nivel 1)
--==============================================================

CREATE TABLE MUNICIPIO (
    ID_MUNICIPIO     INTEGER PRIMARY KEY NOT NULL,
    ID_DEPARTAMENTO  INTEGER NOT NULL,
    NOMBRE_MUNICIPIO VARCHAR(50),
    FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO)
);

CREATE TABLE DISTRITO (
    ID_DISTRITO      INTEGER PRIMARY KEY NOT NULL,
    ID_MUNICIPIO     INTEGER NOT NULL,
    NOMBRE_DISTRITO  VARCHAR(50),
    FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIO (ID_MUNICIPIO)
);

CREATE TABLE HABILIDAD (
    ID_HABILIDAD           INTEGER PRIMARY KEY NOT NULL,
    ID_CATEGORIA_HABILIDAD INTEGER NOT NULL,
    NOMBRE_HABILIDAD       VARCHAR(100),
    FOREIGN KEY (ID_CATEGORIA_HABILIDAD) REFERENCES CATEGORIA_HABILIDAD (ID_CATEGORIA_HABILIDAD)
);

CREATE TABLE EMPRESA (
    ID_EMPRESA       INTEGER PRIMARY KEY NOT NULL,
    ID_DISTRITO      INTEGER NOT NULL,
    NOMBRE_EMPRESA   VARCHAR(150),
    CONTACTO_DIRECTO VARCHAR(100),
    NIT              VARCHAR(20),
    FOREIGN KEY (ID_DISTRITO) REFERENCES DISTRITO (ID_DISTRITO)
);

CREATE TABLE OFERTA_ACADEMICA (
    ID_OFERTA_ACADEMICA INTEGER PRIMARY KEY NOT NULL,
    ID_INSTITUCION      INTEGER,
    ID_GRADO_ACADEMICO  INTEGER,
    FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION (ID_INSTITUCION),
    FOREIGN KEY (ID_GRADO_ACADEMICO) REFERENCES GRADO_ACADEMICO (ID_GRADO_ACADEMICO)
);

--==============================================================
-- Entidades Principales y Relaciones Complejas
--==============================================================

CREATE TABLE POSTULANTE (
    ID_POSTULANTE      INTEGER PRIMARY KEY NOT NULL,
    ID_USUARIO         INTEGER,
    ID_GENERO          INTEGER NOT NULL,
    ID_DISTRITO        INTEGER,
    ID_TIPO_DOCUMENTO  INTEGER NOT NULL,
    NOMBRE             VARCHAR(100),
    APELLIDO           VARCHAR(100),
    FECHA_NACIMIENTO   DATE,
    NUM_DOCUMENTO      VARCHAR(20),
    NUP                VARCHAR(20),
    DIRECCION_DETALLE  VARCHAR(250),
    TELEFONO_CASA      VARCHAR(15),
    TELEFONO_CELULAR   VARCHAR(15),
    EMAIL              VARCHAR(100),
    FOREIGN KEY (ID_GENERO) REFERENCES GENERO (ID_GENERO),
    FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO),
    FOREIGN KEY (ID_DISTRITO) REFERENCES DISTRITO (ID_DISTRITO)
);

CREATE TABLE USUARIO (
    ID_USUARIO    INTEGER PRIMARY KEY NOT NULL,
    ID_POSTULANTE INTEGER NOT NULL,
    USERNAME      VARCHAR(30),
    PASSWORD      VARCHAR(10),
    ROL           VARCHAR(20),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE (ID_POSTULANTE)
);

CREATE TABLE CERTIFICACION (
    ID_POSTULANTE        INTEGER NOT NULL,
    ID_CERTIFICACION     INTEGER NOT NULL,
    ID_INSTITUCION       INTEGER NOT NULL,
    NOMBRE_CERTIFICACION VARCHAR(150),
    CODIGO_CERTIFICACION VARCHAR(50),
    FECHA_CERTIFICACION  DATE,
    PRIMARY KEY (ID_POSTULANTE, ID_CERTIFICACION),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE (ID_POSTULANTE),
    FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION (ID_INSTITUCION)
);

CREATE TABLE OFERTA_TRABAJO (
    ID_EMPRESA          INTEGER NOT NULL,
    ID_OFERTA           INTEGER NOT NULL,
    ID_GRADO_ACADEMICO  INTEGER,
    TITULO_PUESTO       VARCHAR(150),
    FECHA_PUBLICACION   DATE,
    FECHA_CADUCIDAD     DATE,
    EXPERIENCIA_ANIOS   INTEGER,
    EDAD_MINIMA         INTEGER,
    EDAD_MAXIMA         INTEGER,
    DESCRIPCION_OFERTA_TRABAJO VARCHAR(5000),
    PRIMARY KEY (ID_EMPRESA, ID_OFERTA),
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID_EMPRESA),
    FOREIGN KEY (ID_GRADO_ACADEMICO) REFERENCES GRADO_ACADEMICO (ID_GRADO_ACADEMICO)
);

CREATE TABLE DETALLE_REQUISITO (
    ID_DETALLE           INTEGER PRIMARY KEY NOT NULL,
    ID_EMPRESA           INTEGER,
    ID_OFERTA            INTEGER,
    DESCRIPCION_REQUISITO VARCHAR(50),
    FOREIGN KEY (ID_EMPRESA, ID_OFERTA) REFERENCES OFERTA_TRABAJO (ID_EMPRESA, ID_OFERTA)
);

CREATE TABLE EXPERIENCIA_LABORAL (
    ID_POSTULANTE       INTEGER NOT NULL,
    ID_EXPERIENCIA      INTEGER NOT NULL,
    ID_EMPRESA          INTEGER,
    PUESTO_TRABAJO      VARCHAR(100),
    FECHA_INICIO        DATE,
    FECHA_FIN           DATE,
    DES_EXP_LABORAL     VARCHAR(500),
    CONTACTO_REFERENCIA VARCHAR(100),
    PRIMARY KEY (ID_POSTULANTE, ID_EXPERIENCIA),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE (ID_POSTULANTE),
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID_EMPRESA)
);

CREATE TABLE FORMACION_ACADEMICA (
    ID_FORMACION        INTEGER PRIMARY KEY NOT NULL,
    ID_OFERTA_ACADEMICA INTEGER,
    ID_POSTULANTE       INTEGER NOT NULL,
    TITULO_OBTENIDO     VARCHAR(150),
    FECHA_OBTENCION     DATE,
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE (ID_POSTULANTE),
    FOREIGN KEY (ID_OFERTA_ACADEMICA) REFERENCES OFERTA_ACADEMICA (ID_OFERTA_ACADEMICA)
);

CREATE TABLE HABILIDAD_POSTULANTE (
    ID_HABILIDAD            INTEGER NOT NULL,
    ID_POSTULANTE           INTEGER NOT NULL,
    ID_HABILIDAD_POSTULANTE INTEGER NOT NULL,
    NIVEL_DESTREZA          VARCHAR(20),
    PRIMARY KEY (ID_HABILIDAD, ID_POSTULANTE, ID_HABILIDAD_POSTULANTE),
    FOREIGN KEY (ID_HABILIDAD) REFERENCES HABILIDAD (ID_HABILIDAD),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE (ID_POSTULANTE)
);

CREATE TABLE POSTULACION (
    ID_EMPRESA        INTEGER NOT NULL,
    ID_OFERTA         INTEGER NOT NULL,
    ID_POSTULANTE     INTEGER NOT NULL,
    ID_POSTULACION    INTEGER NOT NULL,
    FECHA_APLICACION  DATE,
    ESTADO_PROCESO    VARCHAR(50),
    PRIMARY KEY (ID_EMPRESA, ID_OFERTA, ID_POSTULANTE, ID_POSTULACION),
    FOREIGN KEY (ID_EMPRESA, ID_OFERTA) REFERENCES OFERTA_TRABAJO (ID_EMPRESA, ID_OFERTA),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE (ID_POSTULANTE)
);

CREATE TABLE RED_SOCIAL_POSTULANTE (
    ID_RED_POSTUALNTE INTEGER PRIMARY KEY NOT NULL,
    ID_POSTULANTE     INTEGER,
    ID_RED_SOCIAL     INTEGER,
    URL_PERFIL        VARCHAR(30),
    FOREIGN KEY (ID_RED_SOCIAL) REFERENCES RED_SOCIAL (ID_RED_SOCIAL),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE (ID_POSTULANTE)
);

--==============================================================
-- Índices Adicionales
--==============================================================
CREATE INDEX IDX_RELATIONSHIP_MUNICIPIO ON MUNICIPIO (ID_DEPARTAMENTO);
CREATE INDEX IDX_RELATIONSHIP_DISTRITO ON DISTRITO (ID_MUNICIPIO);
CREATE INDEX IDX_OFERTA_TRABAJO_GRADO ON OFERTA_TRABAJO (ID_GRADO_ACADEMICO);

-- Habilitar llaves foráneas
PRAGMA foreign_keys = ON;
"""

statements = [s.strip() for s in sql_script.split(';') if s.strip() and not s.strip().startswith('--')]

for statement in statements:
    if statement:
        try:
            cursor.execute(statement)
        except Exception as e:
            print(f"Error ejecutando: {statement[:50]}...")
            print(f"Detalle: {e}")

conn.commit()

print(f"Base de datos creada exitosamente en: {db_path}")
print(f"Tamaño: {os.path.getsize(db_path)} bytes")

tables = cursor.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;").fetchall()
print(f"Tablas creadas: {len(tables)}")
for table in tables:
    count = cursor.execute(f"SELECT COUNT(*) FROM {table[0]}").fetchone()[0]
    print(f"  - {table[0]}: {count} registros")

conn.close()