import sqlite3
import os

db_path = os.path.join(os.path.dirname(__file__), 'app', 'src', 'main', 'assets', 'bolsadetabajo.db')

os.makedirs(os.path.dirname(db_path), exist_ok=True)

if os.path.exists(db_path):
    os.remove(db_path)

conn = sqlite3.connect(db_path)
cursor = conn.cursor()

sql_script = """
PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS RED_SOCIAL_POSTULANTE;
DROP TABLE IF EXISTS POSTULACION;
DROP TABLE IF EXISTS HABILIDAD_POSTULANTE;
DROP TABLE IF EXISTS FORMACION_ACADEMICA;
DROP TABLE IF EXISTS EXPERIENCIA_LABORAL;
DROP TABLE IF EXISTS CERTIFICACION;
DROP TABLE IF EXISTS OFERTA_ACADEMICA;
DROP TABLE IF EXISTS DETALLE_REQUISITO;
DROP TABLE IF EXISTS OFERTA_TRABAJO;
DROP TABLE IF EXISTS HABILIDAD;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS POSTULANTE;
DROP TABLE IF EXISTS EMPRESA;
DROP TABLE IF EXISTS RED_SOCIAL;
DROP TABLE IF EXISTS GRADO_ACADEMICO;
DROP TABLE IF EXISTS INSTITUCION;
DROP TABLE IF EXISTS DISTRITO;
DROP TABLE IF EXISTS MUNICIPIO;
DROP TABLE IF EXISTS DEPARTAMENTO;
DROP TABLE IF EXISTS TIPO_DOCUMENTO;
DROP TABLE IF EXISTS GENERO;
DROP TABLE IF EXISTS CATEGORIA_HABILIDAD;

PRAGMA foreign_keys = ON;

-- Tablas AUTOINCREMENTALES (7)

CREATE TABLE CATEGORIA_HABILIDAD (
    ID_CATEGORIA_HABILIDAD INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE_CATEGORIA VARCHAR(50)
);

CREATE TABLE GENERO (
    ID_GENERO INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE_GENERO VARCHAR(20)
);

CREATE TABLE TIPO_DOCUMENTO (
    ID_TIPO_DOCUMENTO INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE_TIPO VARCHAR(25)
);

CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE_DEPARTAMENTO VARCHAR(50)
);

CREATE TABLE GRADO_ACADEMICO (
    ID_GRADO_ACADEMICO INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE_GRADO VARCHAR(50)
);

CREATE TABLE RED_SOCIAL (
    ID_RED_SOCIAL INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE_RED VARCHAR(50)
);

CREATE TABLE USUARIO (
    ID_USUARIO INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME VARCHAR(30),
    PASSWORD VARCHAR(128),
    ROL VARCHAR(20)
);

-- Tablas con PK Compuesta

CREATE TABLE MUNICIPIO (
    ID_DEPARTAMENTO INTEGER NOT NULL,
    ID_MUNICIPIO INTEGER NOT NULL,
    NOMBRE_MUNICIPIO VARCHAR(50),
    PRIMARY KEY (ID_DEPARTAMENTO, ID_MUNICIPIO),
    FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO)
);

CREATE TABLE DISTRITO (
    ID_DEPARTAMENTO INTEGER NOT NULL,
    ID_MUNICIPIO INTEGER NOT NULL,
    ID_DISTRITO INTEGER NOT NULL,
    NOMBRE_DISTRITO VARCHAR(50),
    PRIMARY KEY (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_DISTRITO),
    FOREIGN KEY (ID_DEPARTAMENTO, ID_MUNICIPIO) REFERENCES MUNICIPIO (ID_DEPARTAMENTO, ID_MUNICIPIO)
);

CREATE TABLE OFERTA_TRABAJO (
    NIT VARCHAR(20) NOT NULL,
    ID_OFERTA VARCHAR(10) NOT NULL,
    ID_GRADO_ACADEMICO INTEGER,
    TITULO_PUESTO VARCHAR(150),
    FECHA_PUBLICACION DATE,
    FECHA_CADUCIDAD DATE,
    EXPERIENCIA_ANIOS INTEGER,
    EDAD_MINIMA INTEGER,
    EDAD_MAXIMA INTEGER,
    DESCRIPCION_OFERTA_TRABAJO VARCHAR(5000),
    PRIMARY KEY (NIT, ID_OFERTA),
    FOREIGN KEY (NIT) REFERENCES EMPRESA (NIT),
    FOREIGN KEY (ID_GRADO_ACADEMICO) REFERENCES GRADO_ACADEMICO (ID_GRADO_ACADEMICO)
);

CREATE TABLE DETALLE_REQUISITO (
    NIT VARCHAR(20) NOT NULL,
    ID_OFERTA VARCHAR(10) NOT NULL,
    ID_DETALLE VARCHAR(10) NOT NULL,
    DESCRIPCION_REQUISITO VARCHAR(100),
    PRIMARY KEY (NIT, ID_OFERTA, ID_DETALLE),
    FOREIGN KEY (NIT, ID_OFERTA) REFERENCES OFERTA_TRABAJO (NIT, ID_OFERTA)
);

CREATE TABLE EXPERIENCIA_LABORAL (
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    NIT VARCHAR(20) NOT NULL,
    ID_EXPERIENCIA VARCHAR(10) NOT NULL,
    PUESTO_TRABAJO VARCHAR(100),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    DESCP_EXPERIENCIA_LABORAL VARCHAR(500),
    CONTACTO_REFERENCIA VARCHAR(100),
    PRIMARY KEY (ID_POSTULANTE, NIT, ID_EXPERIENCIA),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE (ID_POSTULANTE),
    FOREIGN KEY (NIT) REFERENCES EMPRESA (NIT)
);

CREATE TABLE CERTIFICACION (
    ID_CERTIFICACION VARCHAR(10) NOT NULL,
    ID_INSTITUCION VARCHAR(20) NOT NULL,
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    NOMBRE_CERTIFICACION VARCHAR(150),
    CODIGO_CERTIFICACION VARCHAR(50),
    FECHA_CERTIFICACION DATE,
    PRIMARY KEY (ID_CERTIFICACION, ID_INSTITUCION, ID_POSTULANTE),
    FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION (ID_INSTITUCION),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE (ID_POSTULANTE)
);

CREATE TABLE FORMACION_ACADEMICA (
    ID_FORMACION VARCHAR(10) NOT NULL,
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    ID_OFERTA_ACADEMICA VARCHAR(10),
    TITULO_OBTENIDO VARCHAR(150),
    FECHA_OBTENCION DATE,
    PRIMARY KEY (ID_FORMACION, ID_POSTULANTE),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE (ID_POSTULANTE),
    FOREIGN KEY (ID_OFERTA_ACADEMICA) REFERENCES OFERTA_ACADEMICA (ID_OFERTA_ACADEMICA)
);

CREATE TABLE HABILIDAD_POSTULANTE (
    ID_CATEGORIA_HABILIDAD INTEGER NOT NULL,
    ID_HABILIDAD VARCHAR(10) NOT NULL,
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    NIVEL_DESTREZA INTEGER,
    PRIMARY KEY (ID_CATEGORIA_HABILIDAD, ID_HABILIDAD, ID_POSTULANTE),
    FOREIGN KEY (ID_CATEGORIA_HABILIDAD, ID_HABILIDAD) REFERENCES HABILIDAD (ID_CATEGORIA_HABILIDAD, ID_HABILIDAD),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE (ID_POSTULANTE)
);

CREATE TABLE POSTULACION (
    ID_POSTULACION VARCHAR(10) NOT NULL,
    NIT VARCHAR(20) NOT NULL,
    ID_OFERTA VARCHAR(10) NOT NULL,
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    FECHA_APLICACION DATE,
    ESTADO_PROCESO VARCHAR(50),
    PRIMARY KEY (ID_POSTULACION),
    FOREIGN KEY (NIT, ID_OFERTA) REFERENCES OFERTA_TRABAJO (NIT, ID_OFERTA),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE (ID_POSTULANTE)
);

CREATE TABLE RED_SOCIAL_POSTULANTE (
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    ID_RED_SOCIAL INTEGER NOT NULL,
    URL_PERFIL VARCHAR(100),
    PRIMARY KEY (ID_POSTULANTE, ID_RED_SOCIAL),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE (ID_POSTULANTE),
    FOREIGN KEY (ID_RED_SOCIAL) REFERENCES RED_SOCIAL (ID_RED_SOCIAL)
);

-- Tablas con PK Manual (VARCHAR)

CREATE TABLE INSTITUCION (
    ID_INSTITUCION VARCHAR(20) PRIMARY KEY,
    NOMBRE_INSTITUCION VARCHAR(150)
);

CREATE TABLE HABILIDAD (
    ID_CATEGORIA_HABILIDAD INTEGER NOT NULL,
    ID_HABILIDAD VARCHAR(10) NOT NULL,
    NOMBRE_HABILIDAD VARCHAR(100),
    PRIMARY KEY (ID_CATEGORIA_HABILIDAD, ID_HABILIDAD),
    FOREIGN KEY (ID_CATEGORIA_HABILIDAD) REFERENCES CATEGORIA_HABILIDAD (ID_CATEGORIA_HABILIDAD)
);

CREATE TABLE EMPRESA (
    NIT VARCHAR(20) PRIMARY KEY,
    ID_DISTRITO_DEPTO INTEGER NOT NULL,
    ID_DISTRITO_MUNICIPIO INTEGER NOT NULL,
    ID_DISTRITO_ID INTEGER NOT NULL,
    NOMBRE_EMPRESA VARCHAR(150),
    CONTACTO_DIRECTO VARCHAR(100),
    FOREIGN KEY (ID_DISTRITO_DEPTO, ID_DISTRITO_MUNICIPIO, ID_DISTRITO_ID) REFERENCES DISTRITO (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_DISTRITO)
);

CREATE TABLE POSTULANTE (
    ID_POSTULANTE VARCHAR(20) PRIMARY KEY,
    ID_GENERO INTEGER NOT NULL,
    ID_TIPO_DOCUMENTO INTEGER NOT NULL,
    ID_DISTRITO_DEPTO INTEGER,
    ID_DISTRITO_MUNICIPIO INTEGER,
    ID_DISTRITO_ID INTEGER,
    NOMBRE VARCHAR(100),
    APELLIDO VARCHAR(100),
    FECHA_NACIMIENTO DATE,
    NUM_DOCUMENTO VARCHAR(20),
    NUP VARCHAR(20),
    DIRECCION_DETALLE VARCHAR(250),
    TELEFONO_CASA VARCHAR(15),
    TELEFONO_CELULAR VARCHAR(15),
    EMAIL VARCHAR(100),
    FOREIGN KEY (ID_GENERO) REFERENCES GENERO (ID_GENERO),
    FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO),
    FOREIGN KEY (ID_DISTRITO_DEPTO, ID_DISTRITO_MUNICIPIO, ID_DISTRITO_ID) REFERENCES DISTRITO (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_DISTRITO)
);

CREATE TABLE OFERTA_ACADEMICA (
    ID_OFERTA_ACADEMICA VARCHAR(10) PRIMARY KEY,
    ID_GRADO_ACADEMICO INTEGER,
    ID_INSTITUCION VARCHAR(20),
    FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION (ID_INSTITUCION),
    FOREIGN KEY (ID_GRADO_ACADEMICO) REFERENCES GRADO_ACADEMICO (ID_GRADO_ACADEMICO)
);

-- Indices

CREATE INDEX IDX_MUNICIPIO_DEPTO ON MUNICIPIO (ID_DEPARTAMENTO);
CREATE INDEX IDX_DISTRITO_MUNICIPIO ON DISTRITO (ID_DEPARTAMENTO, ID_MUNICIPIO);
CREATE INDEX IDX_HABILIDAD_CATEGORIA ON HABILIDAD (ID_CATEGORIA_HABILIDAD);

CREATE INDEX IDX_EMPRESA_DISTRITO ON EMPRESA (ID_DISTRITO_DEPTO, ID_DISTRITO_MUNICIPIO, ID_DISTRITO_ID);
CREATE INDEX IDX_POSTULANTE_GENERO ON POSTULANTE (ID_GENERO);
CREATE INDEX IDX_POSTULANTE_TIPO_DOC ON POSTULANTE (ID_TIPO_DOCUMENTO);
CREATE INDEX IDX_POSTULANTE_DISTRITO ON POSTULANTE (ID_DISTRITO_DEPTO, ID_DISTRITO_MUNICIPIO, ID_DISTRITO_ID);
CREATE INDEX IDX_OFERTA_GRADO ON OFERTA_TRABAJO (ID_GRADO_ACADEMICO);
CREATE INDEX IDX_DETALLE_OFERTA ON DETALLE_REQUISITO (NIT, ID_OFERTA);
CREATE INDEX IDX_EXP_POSTULANTE ON EXPERIENCIA_LABORAL (ID_POSTULANTE);
CREATE INDEX IDX_EXP_EMPRESA ON EXPERIENCIA_LABORAL (NIT);
CREATE INDEX IDX_CERT_POSTULANTE ON CERTIFICACION (ID_POSTULANTE);
CREATE INDEX IDX_CERT_INSTITUCION ON CERTIFICACION (ID_INSTITUCION);
CREATE INDEX IDX_FORM_POSTULANTE ON FORMACION_ACADEMICA (ID_POSTULANTE);
CREATE INDEX IDX_HAB_POST_POSTULANTE ON HABILIDAD_POSTULANTE (ID_POSTULANTE);
CREATE INDEX IDX_HAB_POST_HABILIDAD ON HABILIDAD_POSTULANTE (ID_HABILIDAD);
CREATE INDEX IDX_POSTULACION_POSTULANTE ON POSTULACION (ID_POSTULANTE);
CREATE INDEX IDX_POSTULACION_OFERTA ON POSTULACION (NIT, ID_OFERTA);
CREATE INDEX IDX_RED_POST_POSTULANTE ON RED_SOCIAL_POSTULANTE (ID_POSTULANTE);
CREATE INDEX IDX_OA_INSTITUCION ON OFERTA_ACADEMICA (ID_INSTITUCION);
CREATE INDEX IDX_OA_GRADO ON OFERTA_ACADEMICA (ID_GRADO_ACADEMICO);

-- Triggers Semanticos (6)

CREATE TRIGGER TR_POSTULANTE_EDAD BEFORE INSERT ON POSTULANTE
FOR EACH ROW BEGIN
    SELECT CASE WHEN NEW.FECHA_NACIMIENTO > date('now')
    THEN RAISE(ABORT, 'La fecha de nacimiento no puede ser futura') END;
    SELECT CASE WHEN (strftime('%Y', 'now') - strftime('%Y', NEW.FECHA_NACIMIENTO)) < 18
    THEN RAISE(ABORT, 'El postulante debe ser mayor de edad') END;
END;

CREATE TRIGGER TR_OFERTA_RANGO_EDAD BEFORE INSERT ON OFERTA_TRABAJO
FOR EACH ROW BEGIN
    SELECT CASE WHEN NEW.EDAD_MINIMA > NEW.EDAD_MAXIMA
    THEN RAISE(ABORT, 'Edad minima no puede ser mayor a la maxima') END;
END;

CREATE TRIGGER TR_OFERTA_VIGENCIA BEFORE INSERT ON OFERTA_TRABAJO
FOR EACH ROW BEGIN
    SELECT CASE WHEN NEW.FECHA_CADUCIDAD <= NEW.FECHA_PUBLICACION
    THEN RAISE(ABORT, 'La oferta ya caduco o fecha invalida') END;
END;

CREATE TRIGGER TR_EXP_LABORAL_FECHAS BEFORE INSERT ON EXPERIENCIA_LABORAL
FOR EACH ROW BEGIN
    SELECT CASE WHEN NEW.FECHA_INICIO >= NEW.FECHA_FIN
    THEN RAISE(ABORT, 'Fecha inicio debe ser menor a fecha fin') END;
END;

CREATE TRIGGER TR_HABILIDAD_NIVEL BEFORE INSERT ON HABILIDAD_POSTULANTE
FOR EACH ROW BEGIN
    SELECT CASE WHEN NEW.NIVEL_DESTREZA NOT IN (1, 2, 3)
    THEN RAISE(ABORT, 'Nivel de destreza debe ser 1, 2 o 3') END;
END;

CREATE TRIGGER TR_USUARIO_FORMATO BEFORE INSERT ON USUARIO
FOR EACH ROW BEGIN
    SELECT CASE WHEN LENGTH(NEW.PASSWORD) < 8
    THEN RAISE(ABORT, 'Password minimo 8 caracteres') END;
END;

-- Triggers de Cascada (3)

CREATE TRIGGER TR_DEL_DEPARTAMENTO BEFORE DELETE ON DEPARTAMENTO
FOR EACH ROW BEGIN
    DELETE FROM MUNICIPIO WHERE ID_DEPARTAMENTO = OLD.ID_DEPARTAMENTO;
END;

CREATE TRIGGER TR_DEL_CATEGORIA BEFORE DELETE ON CATEGORIA_HABILIDAD
FOR EACH ROW BEGIN
    DELETE FROM HABILIDAD_POSTULANTE WHERE ID_CATEGORIA_HABILIDAD = OLD.ID_CATEGORIA_HABILIDAD;
    DELETE FROM HABILIDAD WHERE ID_CATEGORIA_HABILIDAD = OLD.ID_CATEGORIA_HABILIDAD;
END;

CREATE TRIGGER TR_DEL_POSTULANTE BEFORE DELETE ON POSTULANTE
FOR EACH ROW BEGIN
    DELETE FROM POSTULACION WHERE ID_POSTULANTE = OLD.ID_POSTULANTE;
    DELETE FROM EXPERIENCIA_LABORAL WHERE ID_POSTULANTE = OLD.ID_POSTULANTE;
    DELETE FROM FORMACION_ACADEMICA WHERE ID_POSTULANTE = OLD.ID_POSTULANTE;
    DELETE FROM CERTIFICACION WHERE ID_POSTULANTE = OLD.ID_POSTULANTE;
    DELETE FROM HABILIDAD_POSTULANTE WHERE ID_POSTULANTE = OLD.ID_POSTULANTE;
    DELETE FROM RED_SOCIAL_POSTULANTE WHERE ID_POSTULANTE = OLD.ID_POSTULANTE;
END;

-- Triggers de Integridad Referencial (5)

CREATE TRIGGER TR_MUNICIPIO_DEPTO BEFORE INSERT ON MUNICIPIO
FOR EACH ROW BEGIN
    SELECT CASE WHEN (SELECT 1 FROM DEPARTAMENTO WHERE ID_DEPARTAMENTO = NEW.ID_DEPARTAMENTO) IS NULL
    THEN RAISE(ABORT, 'El departamento asociado no existe') END;
END;

CREATE TRIGGER TR_DISTRITO_MUNICIPIO BEFORE INSERT ON DISTRITO
FOR EACH ROW BEGIN
    SELECT CASE WHEN (SELECT 1 FROM MUNICIPIO WHERE ID_DEPARTAMENTO = NEW.ID_DEPARTAMENTO AND ID_MUNICIPIO = NEW.ID_MUNICIPIO) IS NULL
    THEN RAISE(ABORT, 'El municipio asociado no existe') END;
END;

CREATE TRIGGER TR_HABILIDAD_CATEGORIA BEFORE INSERT ON HABILIDAD
FOR EACH ROW BEGIN
    SELECT CASE WHEN (SELECT 1 FROM CATEGORIA_HABILIDAD WHERE ID_CATEGORIA_HABILIDAD = NEW.ID_CATEGORIA_HABILIDAD) IS NULL
    THEN RAISE(ABORT, 'La categoria asociada no existe') END;
END;

CREATE TRIGGER TR_EMPRESA_DISTRITO BEFORE INSERT ON EMPRESA
FOR EACH ROW BEGIN
    SELECT CASE WHEN (SELECT 1 FROM DISTRITO WHERE ID_DEPARTAMENTO = NEW.ID_DISTRITO_DEPTO AND ID_MUNICIPIO = NEW.ID_DISTRITO_MUNICIPIO AND ID_DISTRITO = NEW.ID_DISTRITO_ID) IS NULL
    THEN RAISE(ABORT, 'El distrito asociado no existe') END;
END;

CREATE TRIGGER TR_POSTULANTE_FK BEFORE INSERT ON POSTULANTE
FOR EACH ROW BEGIN
    SELECT CASE WHEN (SELECT 1 FROM GENERO WHERE ID_GENERO = NEW.ID_GENERO) IS NULL
    THEN RAISE(ABORT, 'El genero asociado no existe') END;
    SELECT CASE WHEN (SELECT 1 FROM TIPO_DOCUMENTO WHERE ID_TIPO_DOCUMENTO = NEW.ID_TIPO_DOCUMENTO) IS NULL
    THEN RAISE(ABORT, 'El tipo de documento asociado no existe') END;
END;

PRAGMA foreign_keys = ON;
"""

statements = [s.strip() for s in sql_script.split(';') if s.strip() and not s.strip().startswith('--')]

for statement in statements:
    if statement:
        try:
            cursor.execute(statement)
        except Exception as e:
            print(f"Error ejecutando: {statement[:80]}...")
            print(f"Detalle: {e}")

conn.commit()

print(f"Base de datos creada exitosamente en: {db_path}")
print(f"Tamano: {os.path.getsize(db_path)} bytes")

tables = cursor.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;").fetchall()
print(f"Tablas creadas: {len(tables)}")
for table in tables:
    count = cursor.execute(f"SELECT COUNT(*) FROM {table[0]}").fetchone()[0]
    print(f"  - {table[0]}: {count} registros")

conn.close()
