-- ============================================
-- SCRIPT DDL PARA POWER DESIGNER
-- PKs a nivel tabla, FKs inline
-- ============================================

-- ============================================
-- TABLAS CATALOGO (ALES)
-- ============================================

CREATE TABLE CATEGORIA_HABILIDAD (
    ID_CATEGORIA_HABILIDAD INTEGER NOT NULL,
    NOMBRE_CATEGORIA VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_CATEGORIA_HABILIDAD),
    UNIQUE (NOMBRE_CATEGORIA)
);

CREATE TABLE GENERO (
    ID_GENERO INTEGER NOT NULL,
    NOMBRE_GENERO VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID_GENERO),
    UNIQUE (NOMBRE_GENERO)
);

CREATE TABLE TIPO_DOCUMENTO (
    ID_TIPO_DOCUMENTO INTEGER NOT NULL,
    NOMBRE_TIPO VARCHAR(25) NOT NULL,
    PRIMARY KEY (ID_TIPO_DOCUMENTO),
    UNIQUE (NOMBRE_TIPO)
);

CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO INTEGER NOT NULL,
    NOMBRE_DEPARTAMENTO VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_DEPARTAMENTO),
    UNIQUE (NOMBRE_DEPARTAMENTO)
);

CREATE TABLE GRADO_ACADEMICO (
    ID_GRADO_ACADEMICO INTEGER NOT NULL,
    NOMBRE_GRADO VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_GRADO_ACADEMICO),
    UNIQUE (NOMBRE_GRADO)
);

CREATE TABLE RED_SOCIAL (
    ID_RED_SOCIAL INTEGER NOT NULL,
    NOMBRE_RED VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_RED_SOCIAL),
    UNIQUE (NOMBRE_RED)
);

CREATE TABLE TIPO_CERTIFICACION (
    ID_TIPO_CERTIFICACION INTEGER NOT NULL,
    NOMBRE_TIPO VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_TIPO_CERTIFICACION),
    UNIQUE (NOMBRE_TIPO)
);

CREATE TABLE USUARIO (
    ID_USUARIO INTEGER NOT NULL,
    USERNAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(128),
    ROL VARCHAR(20),
    PRIMARY KEY (ID_USUARIO),
    UNIQUE (USERNAME)
);

-- ============================================
-- TABLAS GEOGRAFICAS
-- ============================================

CREATE TABLE MUNICIPIO (
    ID_DEPARTAMENTO INTEGER NOT NULL,
    ID_MUNICIPIO INTEGER NOT NULL,
    NOMBRE_MUNICIPIO VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_DEPARTAMENTO, ID_MUNICIPIO),
    UNIQUE (ID_DEPARTAMENTO, NOMBRE_MUNICIPIO),
    FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO)
);

CREATE TABLE DISTRITO (
    ID_DEPARTAMENTO INTEGER NOT NULL,
    ID_MUNICIPIO INTEGER NOT NULL,
    ID_DISTRITO INTEGER NOT NULL,
    NOMBRE_DISTRITO VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_DISTRITO),
    UNIQUE (ID_DEPARTAMENTO, ID_MUNICIPIO, NOMBRE_DISTRITO),
    FOREIGN KEY (ID_DEPARTAMENTO, ID_MUNICIPIO) REFERENCES MUNICIPIO (ID_DEPARTAMENTO, ID_MUNICIPIO)
);

-- ============================================
-- TABLAS DE HABILIDADES E INSTITUCIONES
-- ============================================

CREATE TABLE INSTITUCION (
    ID_INSTITUCION VARCHAR(20) NOT NULL,
    NOMBRE_INSTITUCION VARCHAR(150) NOT NULL,
    PRIMARY KEY (ID_INSTITUCION),
    UNIQUE (NOMBRE_INSTITUCION)
);

CREATE TABLE HABILIDAD (
    ID_CATEGORIA_HABILIDAD INTEGER NOT NULL,
    ID_HABILIDAD VARCHAR(10) NOT NULL,
    NOMBRE_HABILIDAD VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_CATEGORIA_HABILIDAD, ID_HABILIDAD),
    UNIQUE (NOMBRE_HABILIDAD),
    FOREIGN KEY (ID_CATEGORIA_HABILIDAD) REFERENCES CATEGORIA_HABILIDAD (ID_CATEGORIA_HABILIDAD)
);

-- ============================================
-- TABLAS DE EMPRESA Y POSTULANTE
-- ============================================

CREATE TABLE EMPRESA (
    NIT VARCHAR(20) NOT NULL,
    ID_DISTRITO_DEPTO INTEGER NOT NULL,
    ID_DISTRITO_MUNICIPIO INTEGER NOT NULL,
    ID_DISTRITO_ID INTEGER NOT NULL,
    NOMBRE_EMPRESA VARCHAR(150) NOT NULL,
    CONTACTO_DIRECTO VARCHAR(100),
    PRIMARY KEY (NIT),
    UNIQUE (NOMBRE_EMPRESA),
    FOREIGN KEY (ID_DISTRITO_DEPTO, ID_DISTRITO_MUNICIPIO, ID_DISTRITO_ID)
        REFERENCES DISTRITO (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_DISTRITO)
);

CREATE TABLE POSTULANTE (
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    ID_GENERO INTEGER NOT NULL,
    ID_TIPO_DOCUMENTO INTEGER NOT NULL,
    NUM_DOCUMENTO VARCHAR(20) NOT NULL,
    ID_GRADO_ACADEMICO INTEGER NOT NULL,
    ID_DISTRITO_DEPTO INTEGER,
    ID_DISTRITO_MUNICIPIO INTEGER,
    ID_DISTRITO_ID INTEGER,
    NOMBRE VARCHAR(100),
    APELLIDO VARCHAR(100),
    FECHA_NACIMIENTO DATE,
    NUP VARCHAR(20) NOT NULL,
    DIRECCION_DETALLE VARCHAR(250),
    TELEFONO_CASA VARCHAR(15),
    TELEFONO_CELULAR VARCHAR(15),
    EMAIL VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_POSTULANTE),
    UNIQUE (NUM_DOCUMENTO),
    UNIQUE (NUP),
    UNIQUE (EMAIL),
    FOREIGN KEY (ID_GENERO) REFERENCES GENERO (ID_GENERO),
    FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO),
    FOREIGN KEY (ID_GRADO_ACADEMICO) REFERENCES GRADO_ACADEMICO (ID_GRADO_ACADEMICO),
    FOREIGN KEY (ID_DISTRITO_DEPTO, ID_DISTRITO_MUNICIPIO, ID_DISTRITO_ID)
        REFERENCES DISTRITO (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_DISTRITO)
);

-- ============================================
-- TABLAS DE OFERTAS
-- ============================================

CREATE TABLE OFERTA_ACADEMICA (
    ID_OFERTA_ACADEMICA VARCHAR(10) NOT NULL,
    ID_GRADO_ACADEMICO INTEGER,
    ID_INSTITUCION VARCHAR(20),
    PRIMARY KEY (ID_OFERTA_ACADEMICA),
    UNIQUE (ID_INSTITUCION, ID_GRADO_ACADEMICO),
    FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION (ID_INSTITUCION),
    FOREIGN KEY (ID_GRADO_ACADEMICO) REFERENCES GRADO_ACADEMICO (ID_GRADO_ACADEMICO)
);

CREATE TABLE OFERTA_TRABAJO (
    NIT VARCHAR(20) NOT NULL,
    ID_OFERTA VARCHAR(10) NOT NULL,
    ID_GRADO_ACADEMICO INTEGER,
    TITULO_PUESTO VARCHAR(150) NOT NULL,
    FECHA_PUBLICACION DATE,
    FECHA_CADUCIDAD DATE,
    EXPERIENCIA_ANIOS INTEGER,
    EDAD_MINIMA INTEGER,
    EDAD_MAXIMA INTEGER,
    DESCRIPCION_OFERTA_TRABAJO VARCHAR(5000),
    PRIMARY KEY (NIT, ID_OFERTA),
    UNIQUE (NIT, TITULO_PUESTO),
    FOREIGN KEY (NIT) REFERENCES EMPRESA (NIT),
    FOREIGN KEY (ID_GRADO_ACADEMICO) REFERENCES GRADO_ACADEMICO (ID_GRADO_ACADEMICO)
);

CREATE TABLE DETALLE_REQUISITO (
    NIT VARCHAR(20) NOT NULL,
    ID_OFERTA VARCHAR(10) NOT NULL,
    ID_DETALLE VARCHAR(10) NOT NULL,
    DESCRIPCION_REQUISITO VARCHAR(100) NOT NULL,
    PRIMARY KEY (NIT, ID_OFERTA, ID_DETALLE),
    UNIQUE (NIT, ID_OFERTA, DESCRIPCION_REQUISITO),
    FOREIGN KEY (NIT, ID_OFERTA) REFERENCES OFERTA_TRABAJO (NIT, ID_OFERTA)
);

-- ============================================
-- TABLAS DE POSTULANTE
-- ============================================

CREATE TABLE EXPERIENCIA_LABORAL (
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    NIT VARCHAR(20) NOT NULL,
    ID_EXPERIENCIA VARCHAR(10) NOT NULL,
    PUESTO_TRABAJO VARCHAR(100) NOT NULL,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    DESCP_EXPERIENCIA_LABORAL VARCHAR(500),
    CONTACTO_REFERENCIA VARCHAR(100),
    PRIMARY KEY (ID_POSTULANTE, NIT, ID_EXPERIENCIA),
    UNIQUE (ID_POSTULANTE, NIT, PUESTO_TRABAJO),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE (ID_POSTULANTE),
    FOREIGN KEY (NIT) REFERENCES EMPRESA (NIT)
);

CREATE TABLE CERTIFICACION (
    ID_CERTIFICACION VARCHAR(10) NOT NULL,
    ID_INSTITUCION VARCHAR(20) NOT NULL,
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    ID_TIPO_CERTIFICACION INTEGER,
    NOMBRE_CERTIFICACION VARCHAR(150) NOT NULL,
    FECHA_CERTIFICACION DATE,
    PERIODO VARCHAR(50),
    PRIMARY KEY (ID_CERTIFICACION, ID_INSTITUCION, ID_POSTULANTE),
    UNIQUE (ID_POSTULANTE, NOMBRE_CERTIFICACION),
    FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION (ID_INSTITUCION),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE (ID_POSTULANTE),
    FOREIGN KEY (ID_TIPO_CERTIFICACION) REFERENCES TIPO_CERTIFICACION (ID_TIPO_CERTIFICACION)
);

CREATE TABLE FORMACION_ACADEMICA (
    ID_FORMACION VARCHAR(10) NOT NULL,
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    ID_OFERTA_ACADEMICA VARCHAR(10),
    TITULO_OBTENIDO VARCHAR(150),
    PERIODO VARCHAR(50),
    FECHA_OBTENCION DATE,
    PRIMARY KEY (ID_FORMACION, ID_POSTULANTE),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE (ID_POSTULANTE),
    FOREIGN KEY (ID_OFERTA_ACADEMICA) REFERENCES OFERTA_ACADEMICA (ID_OFERTA_ACADEMICA)
);

CREATE TABLE HABILIDAD_POSTULANTE (
    ID_CATEGORIA_HABILIDAD INTEGER NOT NULL,
    ID_HABILIDAD VARCHAR(10) NOT NULL,
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    NIVEL_DESTREZA VARCHAR(12),
    PRIMARY KEY (ID_CATEGORIA_HABILIDAD, ID_HABILIDAD, ID_POSTULANTE),
    FOREIGN KEY (ID_CATEGORIA_HABILIDAD, ID_HABILIDAD)
        REFERENCES HABILIDAD (ID_CATEGORIA_HABILIDAD, ID_HABILIDAD),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE (ID_POSTULANTE)
);

CREATE TABLE POSTULACION (
    ID_POSTULACION VARCHAR(10) NOT NULL,
    NIT VARCHAR(20) NOT NULL,
    ID_OFERTA VARCHAR(10) NOT NULL,
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    FECHA_APLICACION DATE,
    ESTADO_PROCESO VARCHAR(50),
    PRIMARY KEY (ID_POSTULACION),
    UNIQUE (ID_POSTULANTE, NIT, ID_OFERTA),
    FOREIGN KEY (NIT, ID_OFERTA) REFERENCES OFERTA_TRABAJO (NIT, ID_OFERTA),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE (ID_POSTULANTE)
);

CREATE TABLE RED_SOCIAL_POSTULANTE (
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    ID_RED_SOCIAL INTEGER NOT NULL,
    URL_PERFIL VARCHAR(100),
    PRIMARY KEY (ID_POSTULANTE, ID_RED_SOCIAL),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE (ID_POSTULANTE),
    FOREIGN KEY (ID_RED_SOCIAL) REFERENCES RED_SOCIAL (ID_RED_SOCIAL)
);

-- ============================================
-- INDICES (22)
-- ============================================

CREATE INDEX IDX_MUNICIPIO_DEPTO ON MUNICIPIO (ID_DEPARTAMENTO);
CREATE INDEX IDX_DISTRITO_MUNICIPIO ON DISTRITO (ID_DEPARTAMENTO, ID_MUNICIPIO);
CREATE INDEX IDX_HABILIDAD_CATEGORIA ON HABILIDAD (ID_CATEGORIA_HABILIDAD);
CREATE INDEX IDX_EMPRESA_DISTRITO ON EMPRESA (ID_DISTRITO_DEPTO, ID_DISTRITO_MUNICIPIO, ID_DISTRITO_ID);
CREATE INDEX IDX_POSTULANTE_GENERO ON POSTULANTE (ID_GENERO);
CREATE INDEX IDX_POSTULANTE_TIPO_DOC ON POSTULANTE (ID_TIPO_DOCUMENTO);
CREATE INDEX IDX_POSTULANTE_DISTRITO ON POSTULANTE (ID_DISTRITO_DEPTO, ID_DISTRITO_MUNICIPIO, ID_DISTRITO_ID);
CREATE INDEX IDX_OFERTA_GRADO ON OFERTA_TRABAJO (ID_GRADO_ACADEMICO);
CREATE INDEX IDX_DETALLE_OFERTA ON DETALLE_REQUISITO (NIT, ID_OFERTA);
CREATE INDEX IDX_EXP_POSTULANTE ON EXPERIENCIA_LABORAL (ID_POSTULANTE);
CREATE INDEX IDX_EXP_EMPRESA ON EXPERIENCIA_LABORAL (NIT);
CREATE INDEX IDX_CERT_POSTULANTE ON CERTIFICACION (ID_POSTULANTE);
CREATE INDEX IDX_CERT_INSTITUCION ON CERTIFICACION (ID_INSTITUCION);
CREATE INDEX IDX_FORM_POSTULANTE ON FORMACION_ACADEMICA (ID_POSTULANTE);
CREATE INDEX IDX_HAB_POST_POSTULANTE ON HABILIDAD_POSTULANTE (ID_POSTULANTE);
CREATE INDEX IDX_HAB_POST_HABILIDAD ON HABILIDAD_POSTULANTE (ID_HABILIDAD);
CREATE INDEX IDX_POSTULACION_POSTULANTE ON POSTULACION (ID_POSTULANTE);
CREATE INDEX IDX_POSTULACION_OFERTA ON POSTULACION (NIT, ID_OFERTA);
CREATE INDEX IDX_RED_POST_POSTULANTE ON RED_SOCIAL_POSTULANTE (ID_POSTULANTE);
CREATE INDEX IDX_OA_INSTITUCION ON OFERTA_ACADEMICA (ID_INSTITUCION);
CREATE INDEX IDX_OA_GRADO ON OFERTA_ACADEMICA (ID_GRADO_ACADEMICO);
