-- ============================================================
-- ESCOMA COMPLETO - BOLSA DE TRABAJO (MySQL/MariaDB)
-- 23 tablas + 21 índices + 47 triggers (uno por validación)
-- SIN NECESIDAD DE CAMBIAR EL DELIMITADOR
 -- Funciona con ; por defecto en phpMyAdmin
-- ============================================================
-- INSTRUCCIÓN: Pega TODO y ejecuta. Nada más.
-- ============================================================

-- ============================================================
-- 1. DROP TABLES (orden inverso)
-- ============================================================

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS RED_SOCIAL_POSTULANTE;
DROP TABLE IF EXISTS POSTULACION;
DROP TABLE IF EXISTS HABILIDAD_POSTULANTE;
DROP TABLE IF EXISTS FORMACION_ACADEMICA;
DROP TABLE IF EXISTS EXPERIENCIA_LABORAL;
DROP TABLE IF EXISTS CERTIFICACION;
DROP TABLE IF EXISTS OFERTA_ACADEMICA;
DROP TABLE IF EXISTS DETALLE_REQUISITO;
DROP TABLE IF EXISTS OFERTA_TRABAJO;
DROP TABLE IF EXISTS HABILIDAD;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS POSTULANTE;
DROP TABLE IF EXISTS EMPRESA;
DROP TABLE IF EXISTS RED_SOCIAL;
DROP TABLE IF EXISTS TIPO_CERTIFICACION;
DROP TABLE IF EXISTS GRADO_ACADEMICO;
DROP TABLE IF EXISTS INSTITUCION;
DROP TABLE IF EXISTS DISTRITO;
DROP TABLE IF EXISTS MUNICIPIO;
DROP TABLE IF EXISTS DEPARTAMENTO;
DROP TABLE IF EXISTS TIPO_DOCUMENTO;
DROP TABLE IF EXISTS GENERO;
DROP TABLE IF EXISTS CATEGORIA_HABILIDAD;

DROP TABLE IF EXISTS temp_triggers_log;

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================================
-- 2. CREATE TABLES (23)
-- ============================================================

-- 2.1 AUTOINCREMENTALES (8)

CREATE TABLE CATEGORIA_HABILIDAD (
    ID_CATEGORIA_HABILIDAD INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_CATEGORIA VARCHAR(50) UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE GENERO (
    ID_GENERO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_GENERO VARCHAR(20) UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TIPO_DOCUMENTO (
    ID_TIPO_DOCUMENTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_TIPO VARCHAR(25) UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_DEPARTAMENTO VARCHAR(50) UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE GRADO_ACADEMICO (
    ID_GRADO_ACADEMICO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_GRADO VARCHAR(50) UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE RED_SOCIAL (
    ID_RED_SOCIAL INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_RED VARCHAR(50) UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TIPO_CERTIFICACION (
    ID_TIPO_CERTIFICACION INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_TIPO VARCHAR(100) UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(30) UNIQUE COLLATE utf8mb4_unicode_ci,
    PASSWORD VARCHAR(128),
    ROL VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2.2 PK COMPUESTA (8)

CREATE TABLE MUNICIPIO (
    ID_DEPARTAMENTO INT NOT NULL,
    ID_MUNICIPIO INT NOT NULL,
    NOMBRE_MUNICIPIO VARCHAR(50),
    PRIMARY KEY (ID_DEPARTAMENTO, ID_MUNICIPIO),
    FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    UNIQUE (ID_DEPARTAMENTO, NOMBRE_MUNICIPIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE DISTRITO (
    ID_DEPARTAMENTO INT NOT NULL,
    ID_MUNICIPIO INT NOT NULL,
    ID_DISTRITO INT NOT NULL,
    NOMBRE_DISTRITO VARCHAR(50),
    PRIMARY KEY (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_DISTRITO),
    FOREIGN KEY (ID_DEPARTAMENTO, ID_MUNICIPIO) REFERENCES MUNICIPIO(ID_DEPARTAMENTO, ID_MUNICIPIO),
    UNIQUE (ID_DEPARTAMENTO, ID_MUNICIPIO, NOMBRE_DISTRITO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE INSTITUCION (
    ID_INSTITUCION VARCHAR(20) PRIMARY KEY,
    NOMBRE_INSTITUCION VARCHAR(150) UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE HABILIDAD (
    ID_CATEGORIA_HABILIDAD INT NOT NULL,
    ID_HABILIDAD VARCHAR(10) NOT NULL,
    NOMBRE_HABILIDAD VARCHAR(100) UNIQUE,
    PRIMARY KEY (ID_CATEGORIA_HABILIDAD, ID_HABILIDAD),
    FOREIGN KEY (ID_CATEGORIA_HABILIDAD) REFERENCES CATEGORIA_HABILIDAD(ID_CATEGORIA_HABILIDAD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE EMPRESA (
    NIT VARCHAR(20) PRIMARY KEY,
    ID_DISTRITO_DEPTO INT NOT NULL,
    ID_DISTRITO_MUNICIPIO INT NOT NULL,
    ID_DISTRITO_ID INT NOT NULL,
    NOMBRE_EMPRESA VARCHAR(150) UNIQUE,
    CONTACTO_DIRECTO VARCHAR(100),
    FOREIGN KEY (ID_DISTRITO_DEPTO, ID_DISTRITO_MUNICIPIO, ID_DISTRITO_ID) REFERENCES DISTRITO(ID_DEPARTAMENTO, ID_MUNICIPIO, ID_DISTRITO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE OFERTA_ACADEMICA (
    ID_OFERTA_ACADEMICA VARCHAR(10) PRIMARY KEY,
    ID_GRADO_ACADEMICO INT,
    ID_INSTITUCION VARCHAR(20),
    FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION(ID_INSTITUCION),
    FOREIGN KEY (ID_GRADO_ACADEMICO) REFERENCES GRADO_ACADEMICO(ID_GRADO_ACADEMICO),
    UNIQUE (ID_INSTITUCION, ID_GRADO_ACADEMICO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE POSTULANTE (
    ID_POSTULANTE VARCHAR(20) PRIMARY KEY,
    ID_GENERO INT NOT NULL,
    ID_TIPO_DOCUMENTO INT NOT NULL,
    NUM_DOCUMENTO VARCHAR(20) UNIQUE,
    ID_GRADO_ACADEMICO INT NOT NULL,
    ID_DISTRITO_DEPTO INT,
    ID_DISTRITO_MUNICIPIO INT,
    ID_DISTRITO_ID INT,
    NOMBRE VARCHAR(100),
    APELLIDO VARCHAR(100),
    FECHA_NACIMIENTO DATE,
    NUP VARCHAR(20) UNIQUE,
    DIRECCION_DETALLE VARCHAR(250),
    TELEFONO_CASA VARCHAR(15),
    TELEFONO_CELULAR VARCHAR(15),
    EMAIL VARCHAR(100) UNIQUE COLLATE utf8mb4_unicode_ci,
    FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID_GENERO),
    FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES TIPO_DOCUMENTO(ID_TIPO_DOCUMENTO),
    FOREIGN KEY (ID_GRADO_ACADEMICO) REFERENCES GRADO_ACADEMICO(ID_GRADO_ACADEMICO),
    FOREIGN KEY (ID_DISTRITO_DEPTO, ID_DISTRITO_MUNICIPIO, ID_DISTRITO_ID) REFERENCES DISTRITO(ID_DEPARTAMENTO, ID_MUNICIPIO, ID_DISTRITO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE OFERTA_TRABAJO (
    NIT VARCHAR(20) NOT NULL,
    ID_OFERTA VARCHAR(10) NOT NULL,
    ID_GRADO_ACADEMICO INT,
    TITULO_PUESTO VARCHAR(150),
    FECHA_PUBLICACION DATE,
    FECHA_CADUCIDAD DATE,
    EXPERIENCIA_ANIOS INT,
    EDAD_MINIMA INT,
    EDAD_MAXIMA INT,
    DESCRIPCION_OFERTA_TRABAJO VARCHAR(5000),
    PRIMARY KEY (NIT, ID_OFERTA),
    FOREIGN KEY (NIT) REFERENCES EMPRESA(NIT),
    FOREIGN KEY (ID_GRADO_ACADEMICO) REFERENCES GRADO_ACADEMICO(ID_GRADO_ACADEMICO),
    UNIQUE (NIT, TITULO_PUESTO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE DETALLE_REQUISITO (
    NIT VARCHAR(20) NOT NULL,
    ID_OFERTA VARCHAR(10) NOT NULL,
    ID_DETALLE VARCHAR(10) NOT NULL,
    DESCRIPCION_REQUISITO VARCHAR(100),
    PRIMARY KEY (NIT, ID_OFERTA, ID_DETALLE),
    FOREIGN KEY (NIT, ID_OFERTA) REFERENCES OFERTA_TRABAJO(NIT, ID_OFERTA),
    UNIQUE (NIT, ID_OFERTA, DESCRIPCION_REQUISITO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE EXPERIENCIA_LABORAL (
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    NIT VARCHAR(20) NOT NULL,
    ID_EXPERIENCIA VARCHAR(10) NOT NULL,
    PUESTO_TRABAJO VARCHAR(100),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    DESCP_EXPERIENCIA_LABORAL VARCHAR(500),
    CONTACTO_REFERENCIA VARCHAR(100),
    PRIMARY KEY (ID_POSTULANTE, NIT, ID_EXPERIENCIA),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE(ID_POSTULANTE),
    FOREIGN KEY (NIT) REFERENCES EMPRESA(NIT),
    UNIQUE (ID_POSTULANTE, NIT, PUESTO_TRABAJO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE CERTIFICACION (
    ID_CERTIFICACION VARCHAR(10) NOT NULL,
    ID_INSTITUCION VARCHAR(20) NOT NULL,
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    ID_TIPO_CERTIFICACION INT,
    NOMBRE_CERTIFICACION VARCHAR(150),
    FECHA_CERTIFICACION DATE,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    PRIMARY KEY (ID_CERTIFICACION, ID_INSTITUCION, ID_POSTULANTE),
    FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION(ID_INSTITUCION),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE(ID_POSTULANTE),
    FOREIGN KEY (ID_TIPO_CERTIFICACION) REFERENCES TIPO_CERTIFICACION(ID_TIPO_CERTIFICACION),
    UNIQUE (ID_POSTULANTE, NOMBRE_CERTIFICACION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE FORMACION_ACADEMICA (
    ID_FORMACION VARCHAR(10) NOT NULL,
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    ID_OFERTA_ACADEMICA VARCHAR(10),
    TITULO_OBTENIDO VARCHAR(150),
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    FECHA_OBTENCION DATE,
    PRIMARY KEY (ID_FORMACION, ID_POSTULANTE),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE(ID_POSTULANTE),
    FOREIGN KEY (ID_OFERTA_ACADEMICA) REFERENCES OFERTA_ACADEMICA(ID_OFERTA_ACADEMICA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE HABILIDAD_POSTULANTE (
    ID_CATEGORIA_HABILIDAD INT NOT NULL,
    ID_HABILIDAD VARCHAR(10) NOT NULL,
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    NIVEL_DESTREZA VARCHAR(12),
    PRIMARY KEY (ID_CATEGORIA_HABILIDAD, ID_HABILIDAD, ID_POSTULANTE),
    FOREIGN KEY (ID_CATEGORIA_HABILIDAD, ID_HABILIDAD) REFERENCES HABILIDAD(ID_CATEGORIA_HABILIDAD, ID_HABILIDAD),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE(ID_POSTULANTE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE POSTULACION (
    ID_POSTULACION VARCHAR(10) NOT NULL,
    NIT VARCHAR(20) NOT NULL,
    ID_OFERTA VARCHAR(10) NOT NULL,
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    FECHA_APLICACION DATE,
    ESTADO_PROCESO VARCHAR(50),
    PRIMARY KEY (ID_POSTULACION),
    FOREIGN KEY (NIT, ID_OFERTA) REFERENCES OFERTA_TRABAJO(NIT, ID_OFERTA),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE(ID_POSTULANTE),
    UNIQUE (ID_POSTULANTE, NIT, ID_OFERTA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE RED_SOCIAL_POSTULANTE (
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    ID_RED_SOCIAL INT NOT NULL,
    URL_PERFIL VARCHAR(100),
    PRIMARY KEY (ID_POSTULANTE, ID_RED_SOCIAL),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE(ID_POSTULANTE),
    FOREIGN KEY (ID_RED_SOCIAL) REFERENCES RED_SOCIAL(ID_RED_SOCIAL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- 3. INDEXES (21)
-- ============================================================

CREATE INDEX IDX_MUNICIPIO_DEPTO ON MUNICIPIO (ID_DEPARTAMENTO);
CREATE INDEX IDX_DISTRITO_MUNICIPIO ON DISTRITO (ID_DEPARTAMENTO, ID_MUNICIPIO);
CREATE INDEX IDX_HABILIDAD_CATEGORIA ON HABILIDAD (ID_CATEGORIA_HABILIDAD);
CREATE INDEX IDX_EMPRESA_DISTRITO ON EMPRESA (ID_DISTRITO_DEPTO, ID_DISTRITO_MUNICIPIO, ID_DISTRITO_ID);
CREATE INDEX IDX_POSTULANTE_GENERO ON POSTULANTE (ID_GENERO);
CREATE INDEX IDX_POSTULANTE_TIPO_DOC ON POSTULANTE (ID_TIPO_DOCUMENTO);
CREATE INDEX IDX_POSTULANTE_DISTRITO ON POSTULANTE (ID_DISTRITO_DEPTO, ID_DISTRITO_MUNICIPIO, ID_DISTRITO_ID);
CREATE INDEX IDX_OFERTA_GRADO ON OFERTA_TRABAJO (ID_GRADO_ACADEMICO);
CREATE INDEX IDX_DETALLE_OFERTA ON DETALLE_REQUISITO (NIT, ID_OFERTA);
CREATE INDEX IDX_EXP_POSTULANTE ON EXPERIENCIA_LABORAL (ID_POSTULANTE);
CREATE INDEX IDX_EXP_EMPRESA ON EXPERIENCIA_LABORAL (NIT);
CREATE INDEX IDX_CERT_POSTULANTE ON CERTIFICACION (ID_POSTULANTE);
CREATE INDEX IDX_CERT_INSTITUCION ON CERTIFICACION (ID_INSTITUCION);
CREATE INDEX IDX_FORM_POSTULANTE ON FORMACION_ACADEMICA (ID_POSTULANTE);
CREATE INDEX IDX_HAB_POST_POSTULANTE ON HABILIDAD_POSTULANTE (ID_POSTULANTE);
CREATE INDEX IDX_HAB_POST_HABILIDAD ON HABILIDAD_POSTULANTE (ID_HABILIDAD);
CREATE INDEX IDX_POSTULACION_POSTULANTE ON POSTULACION (ID_POSTULANTE);
CREATE INDEX IDX_POSTULACION_OFERTA ON POSTULACION (NIT, ID_OFERTA);
CREATE INDEX IDX_RED_POST_POSTULANTE ON RED_SOCIAL_POSTULANTE (ID_POSTULANTE);
CREATE INDEX IDX_OA_INSTITUCION ON OFERTA_ACADEMICA (ID_INSTITUCION);
CREATE INDEX IDX_OA_GRADO ON OFERTA_ACADEMICA (ID_GRADO_ACADEMICO);

-- ============================================================
-- 4. TRIGGERS (uno por validación, sin BEGIN..END)
-- Todos usan SIGNAL directo, sin IF
-- ============================================================

-- 4.1 POSTULANTE: fecha nacimiento no futura
CREATE TRIGGER TR_POSTULANTE_EDAD_FECHA BEFORE INSERT ON POSTULANTE
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'La fecha de nacimiento no puede ser futura'
WHEN (NEW.FECHA_NACIMIENTO > CURDATE());

CREATE TRIGGER TR_POSTULANTE_EDAD_FECHA_UPD BEFORE UPDATE ON POSTULANTE
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'La fecha de nacimiento no puede ser futura'
WHEN (NEW.FECHA_NACIMIENTO > CURDATE());

-- 4.2 POSTULANTE: edad >= 18
CREATE TRIGGER TR_POSTULANTE_EDAD_18 BEFORE INSERT ON POSTULANTE
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El postulante debe ser mayor de edad'
WHEN (DATE_ADD(NEW.FECHA_NACIMIENTO, INTERVAL 18 YEAR) > CURDATE());

CREATE TRIGGER TR_POSTULANTE_EDAD_18_UPD BEFORE UPDATE ON POSTULANTE
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El postulante debe ser mayor de edad'
WHEN (DATE_ADD(NEW.FECHA_NACIMIENTO, INTERVAL 18 YEAR) > CURDATE());

-- 4.3 POSTULANTE: grado ≠ Bachiller
CREATE TRIGGER TR_POSTULANTE_GRADO BEFORE INSERT ON POSTULANTE
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El postulante debe tener un grado academico superior a Bachiller'
WHEN ((SELECT LOWER(NOMBRE_GRADO) FROM GRADO_ACADEMICO WHERE ID_GRADO_ACADEMICO = NEW.ID_GRADO_ACADEMICO) IN ('bachiller'));

CREATE TRIGGER TR_POSTULANTE_GRADO_UPD BEFORE UPDATE ON POSTULANTE
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El postulante debe tener un grado academico superior a Bachiller'
WHEN ((SELECT LOWER(NOMBRE_GRADO) FROM GRADO_ACADEMICO WHERE ID_GRADO_ACADEMICO = NEW.ID_GRADO_ACADEMICO) IN ('bachiller'));

-- 4.4 OFERTA_TRABAJO: EDAD_MINIMA >= 18
CREATE TRIGGER TR_OFERTA_EDAD_MIN BEFORE INSERT ON OFERTA_TRABAJO
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Edad minima debe ser mayor o igual a 18'
WHEN (NEW.EDAD_MINIMA < 18);

CREATE TRIGGER TR_OFERTA_EDAD_MIN_UPD BEFORE UPDATE ON OFERTA_TRABAJO
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Edad minima debe ser mayor o igual a 18'
WHEN (NEW.EDAD_MINIMA < 18);

-- 4.5 OFERTA_TRABAJO: EDAD_MINIMA <= EDAD_MAXIMA
CREATE TRIGGER TR_OFERTA_EDAD_RANGO BEFORE INSERT ON OFERTA_TRABAJO
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Edad minima no puede ser mayor a la maxima'
WHEN (NEW.EDAD_MINIMA > NEW.EDAD_MAXIMA);

CREATE TRIGGER TR_OFERTA_EDAD_RANGO_UPD BEFORE UPDATE ON OFERTA_TRABAJO
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Edad minima no puede ser mayor a la maxima'
WHEN (NEW.EDAD_MINIMA > NEW.EDAD_MAXIMA);

-- 4.6 OFERTA_TRABAJO: fecha caducidad > publicación
CREATE TRIGGER TR_OFERTA_VIGENCIA BEFORE INSERT ON OFERTA_TRABAJO
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'La oferta ya caduco o fecha invalida'
WHEN (NEW.FECHA_CADUCIDAD <= NEW.FECHA_PUBLICACION);

CREATE TRIGGER TR_OFERTA_VIGENCIA_UPD BEFORE UPDATE ON OFERTA_TRABAJO
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'La oferta ya caduco o fecha invalida'
WHEN (NEW.FECHA_CADUCIDAD <= NEW.FECHA_PUBLICACION);

-- 4.7 POSTULACION: oferta no vencida
CREATE TRIGGER TR_POSTULACION_VIGENCIA BEFORE INSERT ON POSTULACION
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'La oferta de trabajo ha vencido'
WHEN ((SELECT FECHA_CADUCIDAD FROM OFERTA_TRABAJO WHERE NIT = NEW.NIT AND ID_OFERTA = NEW.ID_OFERTA) < CURDATE());

-- 4.8 EXPERIENCIA_LABORAL: FECHA_INICIO < FECHA_FIN
CREATE TRIGGER TR_EXP_FECHAS BEFORE INSERT ON EXPERIENCIA_LABORAL
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha inicio debe ser menor a fecha fin'
WHEN (NEW.FECHA_INICIO >= NEW.FECHA_FIN);

CREATE TRIGGER TR_EXP_FECHAS_UPD BEFORE UPDATE ON EXPERIENCIA_LABORAL
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha inicio debe ser menor a fecha fin'
WHEN (NEW.FECHA_INICIO >= NEW.FECHA_FIN);

-- 4.9 CERTIFICACION: FECHA_INICIO < FECHA_FIN
CREATE TRIGGER TR_CERT_FECHAS_INICIO_FIN BEFORE INSERT ON CERTIFICACION
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha inicio debe ser menor a fecha fin'
WHEN (NEW.FECHA_INICIO >= NEW.FECHA_FIN);

CREATE TRIGGER TR_CERT_FECHAS_INICIO_FIN_UPD BEFORE UPDATE ON CERTIFICACION
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha inicio debe ser menor a fecha fin'
WHEN (NEW.FECHA_INICIO >= NEW.FECHA_FIN);

-- 4.10 CERTIFICACION: FECHA_INICIO no futura
CREATE TRIGGER TR_CERT_FECHAS_INICIO_FUT BEFORE INSERT ON CERTIFICACION
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha inicio no puede ser una fecha futura'
WHEN (NEW.FECHA_INICIO > CURDATE());

CREATE TRIGGER TR_CERT_FECHAS_INICIO_FUT_UPD BEFORE UPDATE ON CERTIFICACION
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha inicio no puede ser una fecha futura'
WHEN (NEW.FECHA_INICIO > CURDATE());

-- 4.11 CERTIFICACION: FECHA_FIN no futura
CREATE TRIGGER TR_CERT_FECHAS_FIN_FUT BEFORE INSERT ON CERTIFICACION
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha fin no puede ser una fecha futura'
WHEN (NEW.FECHA_FIN > CURDATE());

CREATE TRIGGER TR_CERT_FECHAS_FIN_FUT_UPD BEFORE UPDATE ON CERTIFICACION
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha fin no puede ser una fecha futura'
WHEN (NEW.FECHA_FIN > CURDATE());

-- 4.12 CERTIFICACION: FECHA_CERTIFICACION >= FECHA_FIN
CREATE TRIGGER TR_CERT_FECHAS_CERT_FIN BEFORE INSERT ON CERTIFICACION
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de certificacion no puede ser menor a la fecha fin del periodo'
WHEN (NEW.FECHA_CERTIFICACION < NEW.FECHA_FIN);

CREATE TRIGGER TR_CERT_FECHAS_CERT_FIN_UPD BEFORE UPDATE ON CERTIFICACION
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de certificacion no puede ser menor a la fecha fin del periodo'
WHEN (NEW.FECHA_CERTIFICACION < NEW.FECHA_FIN);

-- 4.13 CERTIFICACION: FECHA_CERTIFICACION <= FECHA_FIN + 1 año
CREATE TRIGGER TR_CERT_FECHAS_CERT_ANIO BEFORE INSERT ON CERTIFICACION
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de certificacion no puede exceder un año despues de la fecha fin del periodo'
WHEN (NEW.FECHA_CERTIFICACION > DATE_ADD(NEW.FECHA_FIN, INTERVAL 1 YEAR));

CREATE TRIGGER TR_CERT_FECHAS_CERT_ANIO_UPD BEFORE UPDATE ON CERTIFICACION
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de certificacion no puede exceder un año despues de la fecha fin del periodo'
WHEN (NEW.FECHA_CERTIFICACION > DATE_ADD(NEW.FECHA_FIN, INTERVAL 1 YEAR));

-- 4.14 CERTIFICACION: FECHA_CERTIFICACION no futura
CREATE TRIGGER TR_CERT_FECHAS_CERT_FUT BEFORE INSERT ON CERTIFICACION
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de certificacion no puede ser una fecha futura'
WHEN (NEW.FECHA_CERTIFICACION > CURDATE());

CREATE TRIGGER TR_CERT_FECHAS_CERT_FUT_UPD BEFORE UPDATE ON CERTIFICACION
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de certificacion no puede ser una fecha futura'
WHEN (NEW.FECHA_CERTIFICACION > CURDATE());

-- 4.15 FORMACION_ACADEMICA: FECHA_INICIO < FECHA_FIN
CREATE TRIGGER TR_FORM_FECHAS_INICIO_FIN BEFORE INSERT ON FORMACION_ACADEMICA
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha inicio debe ser menor a fecha fin'
WHEN (NEW.FECHA_INICIO >= NEW.FECHA_FIN);

CREATE TRIGGER TR_FORM_FECHAS_INICIO_FIN_UPD BEFORE UPDATE ON FORMACION_ACADEMICA
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha inicio debe ser menor a fecha fin'
WHEN (NEW.FECHA_INICIO >= NEW.FECHA_FIN);

-- 4.16 FORMACION_ACADEMICA: FECHA_INICIO no futura
CREATE TRIGGER TR_FORM_FECHAS_INICIO_FUT BEFORE INSERT ON FORMACION_ACADEMICA
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha inicio no puede ser una fecha futura'
WHEN (NEW.FECHA_INICIO > CURDATE());

CREATE TRIGGER TR_FORM_FECHAS_INICIO_FUT_UPD BEFORE UPDATE ON FORMACION_ACADEMICA
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha inicio no puede ser una fecha futura'
WHEN (NEW.FECHA_INICIO > CURDATE());

-- 4.17 FORMACION_ACADEMICA: FECHA_FIN no futura
CREATE TRIGGER TR_FORM_FECHAS_FIN_FUT BEFORE INSERT ON FORMACION_ACADEMICA
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha fin no puede ser una fecha futura'
WHEN (NEW.FECHA_FIN > CURDATE());

CREATE TRIGGER TR_FORM_FECHAS_FIN_FUT_UPD BEFORE UPDATE ON FORMACION_ACADEMICA
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha fin no puede ser una fecha futura'
WHEN (NEW.FECHA_FIN > CURDATE());

-- 4.18 FORMACION_ACADEMICA: FECHA_OBTENCION >= FECHA_FIN
CREATE TRIGGER TR_FORM_FECHAS_OBT_FIN BEFORE INSERT ON FORMACION_ACADEMICA
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de obtencion no puede ser menor a la fecha fin del periodo'
WHEN (NEW.FECHA_OBTENCION < NEW.FECHA_FIN);

CREATE TRIGGER TR_FORM_FECHAS_OBT_FIN_UPD BEFORE UPDATE ON FORMACION_ACADEMICA
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de obtencion no puede ser menor a la fecha fin del periodo'
WHEN (NEW.FECHA_OBTENCION < NEW.FECHA_FIN);

-- 4.19 FORMACION_ACADEMICA: FECHA_OBTENCION <= FECHA_FIN + 1 año
CREATE TRIGGER TR_FORM_FECHAS_OBT_ANIO BEFORE INSERT ON FORMACION_ACADEMICA
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de obtencion no puede exceder un año despues de la fecha fin del periodo'
WHEN (NEW.FECHA_OBTENCION > DATE_ADD(NEW.FECHA_FIN, INTERVAL 1 YEAR));

CREATE TRIGGER TR_FORM_FECHAS_OBT_ANIO_UPD BEFORE UPDATE ON FORMACION_ACADEMICA
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de obtencion no puede exceder un año despues de la fecha fin del periodo'
WHEN (NEW.FECHA_OBTENCION > DATE_ADD(NEW.FECHA_FIN, INTERVAL 1 YEAR));

-- 4.20 FORMACION_ACADEMICA: FECHA_OBTENCION no futura
CREATE TRIGGER TR_FORM_FECHAS_OBT_FUT BEFORE INSERT ON FORMACION_ACADEMICA
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de obtencion no puede ser una fecha futura'
WHEN (NEW.FECHA_OBTENCION > CURDATE());

CREATE TRIGGER TR_FORM_FECHAS_OBT_FUT_UPD BEFORE UPDATE ON FORMACION_ACADEMICA
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de obtencion no puede ser una fecha futura'
WHEN (NEW.FECHA_OBTENCION > CURDATE());

-- 4.21 HABILIDAD_POSTULANTE: nivel válido
CREATE TRIGGER TR_HAB_NIVEL BEFORE INSERT ON HABILIDAD_POSTULANTE
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Nivel de destreza debe ser Basico, Intermedio o Avanzado'
WHEN (NEW.NIVEL_DESTREZA NOT IN ('Básico', 'Intermedio', 'Avanzado'));

CREATE TRIGGER TR_HAB_NIVEL_UPD BEFORE UPDATE ON HABILIDAD_POSTULANTE
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Nivel de destreza debe ser Basico, Intermedio o Avanzado'
WHEN (NEW.NIVEL_DESTREZA NOT IN ('Básico', 'Intermedio', 'Avanzado'));

-- 4.22 MUNICIPIO: FK a DEPARTAMENTO
CREATE TRIGGER TR_MUNICIPIO_DEPTO BEFORE INSERT ON MUNICIPIO
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El departamento asociado no existe'
WHEN ((SELECT 1 FROM DEPARTAMENTO WHERE ID_DEPARTAMENTO = NEW.ID_DEPARTAMENTO) IS NULL);

CREATE TRIGGER TR_MUNICIPIO_DEPTO_UPD BEFORE UPDATE ON MUNICIPIO
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El departamento asociado no existe'
WHEN ((SELECT 1 FROM DEPARTAMENTO WHERE ID_DEPARTAMENTO = NEW.ID_DEPARTAMENTO) IS NULL);

-- 4.23 DISTRITO: FK a MUNICIPIO
CREATE TRIGGER TR_DISTRITO_MUNICIPIO BEFORE INSERT ON DISTRITO
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El municipio asociado no existe'
WHEN ((SELECT 1 FROM MUNICIPIO WHERE ID_DEPARTAMENTO = NEW.ID_DEPARTAMENTO AND ID_MUNICIPIO = NEW.ID_MUNICIPIO) IS NULL);

CREATE TRIGGER TR_DISTRITO_MUNICIPIO_UPD BEFORE UPDATE ON DISTRITO
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El municipio asociado no existe'
WHEN ((SELECT 1 FROM MUNICIPIO WHERE ID_DEPARTAMENTO = NEW.ID_DEPARTAMENTO AND ID_MUNICIPIO = NEW.ID_MUNICIPIO) IS NULL);

-- 4.24 HABILIDAD: FK a CATEGORIA_HABILIDAD
CREATE TRIGGER TR_HAB_CATEGORIA BEFORE INSERT ON HABILIDAD
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'La categoria asociada no existe'
WHEN ((SELECT 1 FROM CATEGORIA_HABILIDAD WHERE ID_CATEGORIA_HABILIDAD = NEW.ID_CATEGORIA_HABILIDAD) IS NULL);

CREATE TRIGGER TR_HAB_CATEGORIA_UPD BEFORE UPDATE ON HABILIDAD
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'La categoria asociada no existe'
WHEN ((SELECT 1 FROM CATEGORIA_HABILIDAD WHERE ID_CATEGORIA_HABILIDAD = NEW.ID_CATEGORIA_HABILIDAD) IS NULL);

-- 4.25 EMPRESA: FK a DISTRITO
CREATE TRIGGER TR_EMPRESA_DISTRITO BEFORE INSERT ON EMPRESA
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El distrito asociado no existe'
WHEN ((SELECT 1 FROM DISTRITO WHERE ID_DEPARTAMENTO = NEW.ID_DISTRITO_DEPTO AND ID_MUNICIPIO = NEW.ID_DISTRITO_MUNICIPIO AND ID_DISTRITO = NEW.ID_DISTRITO_ID) IS NULL);

CREATE TRIGGER TR_EMPRESA_DISTRITO_UPD BEFORE UPDATE ON EMPRESA
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El distrito asociado no existe'
WHEN ((SELECT 1 FROM DISTRITO WHERE ID_DEPARTAMENTO = NEW.ID_DISTRITO_DEPTO AND ID_MUNICIPIO = NEW.ID_DISTRITO_MUNICIPIO AND ID_DISTRITO = NEW.ID_DISTRITO_ID) IS NULL);

-- 4.26 POSTULANTE: FK a GENERO
CREATE TRIGGER TR_POSTULANTE_FK_GENERO BEFORE INSERT ON POSTULANTE
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El genero asociado no existe'
WHEN ((SELECT 1 FROM GENERO WHERE ID_GENERO = NEW.ID_GENERO) IS NULL);

CREATE TRIGGER TR_POSTULANTE_FK_GENERO_UPD BEFORE UPDATE ON POSTULANTE
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El genero asociado no existe'
WHEN ((SELECT 1 FROM GENERO WHERE ID_GENERO = NEW.ID_GENERO) IS NULL);

-- 4.27 POSTULANTE: FK a TIPO_DOCUMENTO
CREATE TRIGGER TR_POSTULANTE_FK_TIPODOC BEFORE INSERT ON POSTULANTE
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El tipo de documento asociado no existe'
WHEN ((SELECT 1 FROM TIPO_DOCUMENTO WHERE ID_TIPO_DOCUMENTO = NEW.ID_TIPO_DOCUMENTO) IS NULL);

CREATE TRIGGER TR_POSTULANTE_FK_TIPODOC_UPD BEFORE UPDATE ON POSTULANTE
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El tipo de documento asociado no existe'
WHEN ((SELECT 1 FROM TIPO_DOCUMENTO WHERE ID_TIPO_DOCUMENTO = NEW.ID_TIPO_DOCUMENTO) IS NULL);

-- 4.28 POSTULANTE: FK a GRADO_ACADEMICO (solo si no NULL)
CREATE TRIGGER TR_POSTULANTE_FK_GRADO BEFORE INSERT ON POSTULANTE
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El grado academico asociado no existe'
WHEN (NEW.ID_GRADO_ACADEMICO IS NOT NULL AND (SELECT 1 FROM GRADO_ACADEMICO WHERE ID_GRADO_ACADEMICO = NEW.ID_GRADO_ACADEMICO) IS NULL);

CREATE TRIGGER TR_POSTULANTE_FK_GRADO_UPD BEFORE UPDATE ON POSTULANTE
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El grado academico asociado no existe'
WHEN (NEW.ID_GRADO_ACADEMICO IS NOT NULL AND (SELECT 1 FROM GRADO_ACADEMICO WHERE ID_GRADO_ACADEMICO = NEW.ID_GRADO_ACADEMICO) IS NULL);

-- ============================================================
-- FIN: 23 tablas + 21 índices + 47 triggers
-- ============================================================
