-- ============================================================
-- ESQUEMA BOLSA DE TRABAJO - TABLAS + INDICES
-- Compatible con InfinityFree (phpMyAdmin)
-- Contiene: DROP TRIGGERS + DROP TABLES + CREATE TABLES + INDICES
-- ============================================================
-- INSTRUCCIONES:
-- 1. phpMyAdmin > pestaña SQL > Delimitador: ;
-- 2. Pega este archivo y ejecuta
-- 3. Luego abre esquema_triggers.sql con Delimitador: $$
-- ============================================================

-- ============================================================
-- 1. DROP TRIGGERS (27)
-- ============================================================

DROP TRIGGER IF EXISTS TR_POSTULANTE_EDAD;
DROP TRIGGER IF EXISTS TR_POSTULANTE_EDAD_UPD;
DROP TRIGGER IF EXISTS TR_POSTULANTE_GRADO;
DROP TRIGGER IF EXISTS TR_POSTULANTE_GRADO_UPD;
DROP TRIGGER IF EXISTS TR_OFERTA_RANGO_EDAD;
DROP TRIGGER IF EXISTS TR_OFERTA_RANGO_EDAD_UPD;
DROP TRIGGER IF EXISTS TR_OFERTA_VIGENCIA;
DROP TRIGGER IF EXISTS TR_OFERTA_VIGENCIA_UPD;
DROP TRIGGER IF EXISTS TR_POSTULACION_VIGENCIA;
DROP TRIGGER IF EXISTS TR_EXP_LABORAL_FECHAS;
DROP TRIGGER IF EXISTS TR_EXP_LABORAL_FECHAS_UPD;
DROP TRIGGER IF EXISTS TR_CERTIFICACION_FECHAS;
DROP TRIGGER IF EXISTS TR_CERTIFICACION_FECHAS_UPD;
DROP TRIGGER IF EXISTS TR_FORMACION_FECHAS;
DROP TRIGGER IF EXISTS TR_FORMACION_FECHAS_UPD;
DROP TRIGGER IF EXISTS TR_HABILIDAD_NIVEL;
DROP TRIGGER IF EXISTS TR_HABILIDAD_NIVEL_UPD;
DROP TRIGGER IF EXISTS TR_MUNICIPIO_DEPTO;
DROP TRIGGER IF EXISTS TR_MUNICIPIO_DEPTO_UPD;
DROP TRIGGER IF EXISTS TR_DISTRITO_MUNICIPIO;
DROP TRIGGER IF EXISTS TR_DISTRITO_MUNICIPIO_UPD;
DROP TRIGGER IF EXISTS TR_HABILIDAD_CATEGORIA;
DROP TRIGGER IF EXISTS TR_HABILIDAD_CATEGORIA_UPD;
DROP TRIGGER IF EXISTS TR_EMPRESA_DISTRITO;
DROP TRIGGER IF EXISTS TR_EMPRESA_DISTRITO_UPD;
DROP TRIGGER IF EXISTS TR_POSTULANTE_FK;
DROP TRIGGER IF EXISTS TR_POSTULANTE_FK_UPD;

-- ============================================================
-- 2. DROP TABLES (orden inverso de dependencias)
-- ============================================================

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS RED_SOCIAL_POSTULANTE;
DROP TABLE IF EXISTS POSTULACION;
DROP TABLE IF EXISTS HABILIDAD_POSTULANTE;
DROP TABLE IF EXISTS FORMACION_ACADEMICA;
DROP TABLE IF EXISTS EXPERIENCIA_LABORAL;
DROP TABLE IF EXISTS CERTIFICACION;
DROP TABLE IF EXISTS OFERTA_ACADEMICA;
DROP TABLE IF EXISTS DETALLE_REQUISITO;
DROP TABLE IF EXISTS OFERTA_TRABAJO;
DROP TABLE IF EXISTS HABILIDAD;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS POSTULANTE;
DROP TABLE IF EXISTS EMPRESA;
DROP TABLE IF EXISTS RED_SOCIAL;
DROP TABLE IF EXISTS TIPO_CERTIFICACION;
DROP TABLE IF EXISTS GRADO_ACADEMICO;
DROP TABLE IF EXISTS INSTITUCION;
DROP TABLE IF EXISTS DISTRITO;
DROP TABLE IF EXISTS MUNICIPIO;
DROP TABLE IF EXISTS DEPARTAMENTO;
DROP TABLE IF EXISTS TIPO_DOCUMENTO;
DROP TABLE IF EXISTS GENERO;
DROP TABLE IF EXISTS CATEGORIA_HABILIDAD;

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================================
-- 3. CREATE TABLES (23) - ordenado por dependencias
-- ============================================================

-- 3.1 Tablas sin FK (9)

CREATE TABLE CATEGORIA_HABILIDAD (
    ID_CATEGORIA_HABILIDAD INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_CATEGORIA VARCHAR(50) UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE GENERO (
    ID_GENERO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_GENERO VARCHAR(20) UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TIPO_DOCUMENTO (
    ID_TIPO_DOCUMENTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_TIPO VARCHAR(25) UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_DEPARTAMENTO VARCHAR(50) UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE GRADO_ACADEMICO (
    ID_GRADO_ACADEMICO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_GRADO VARCHAR(50) UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE RED_SOCIAL (
    ID_RED_SOCIAL INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_RED VARCHAR(50) UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TIPO_CERTIFICACION (
    ID_TIPO_CERTIFICACION INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_TIPO VARCHAR(100) UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(30) UNIQUE COLLATE utf8mb4_unicode_ci,
    PASSWORD VARCHAR(128),
    ROL VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE INSTITUCION (
    ID_INSTITUCION VARCHAR(20) PRIMARY KEY,
    NOMBRE_INSTITUCION VARCHAR(150) UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3.2 Tablas con FK a 3.1 (4)

CREATE TABLE MUNICIPIO (
    ID_DEPARTAMENTO INT NOT NULL,
    ID_MUNICIPIO INT NOT NULL,
    NOMBRE_MUNICIPIO VARCHAR(50),
    PRIMARY KEY (ID_DEPARTAMENTO, ID_MUNICIPIO),
    FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    UNIQUE (ID_DEPARTAMENTO, NOMBRE_MUNICIPIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE DISTRITO (
    ID_DEPARTAMENTO INT NOT NULL,
    ID_MUNICIPIO INT NOT NULL,
    ID_DISTRITO INT NOT NULL,
    NOMBRE_DISTRITO VARCHAR(50),
    PRIMARY KEY (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_DISTRITO),
    FOREIGN KEY (ID_DEPARTAMENTO, ID_MUNICIPIO) REFERENCES MUNICIPIO(ID_DEPARTAMENTO, ID_MUNICIPIO),
    UNIQUE (ID_DEPARTAMENTO, ID_MUNICIPIO, NOMBRE_DISTRITO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE HABILIDAD (
    ID_CATEGORIA_HABILIDAD INT NOT NULL,
    ID_HABILIDAD VARCHAR(10) NOT NULL,
    NOMBRE_HABILIDAD VARCHAR(100) UNIQUE,
    PRIMARY KEY (ID_CATEGORIA_HABILIDAD, ID_HABILIDAD),
    FOREIGN KEY (ID_CATEGORIA_HABILIDAD) REFERENCES CATEGORIA_HABILIDAD(ID_CATEGORIA_HABILIDAD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE EMPRESA (
    NIT VARCHAR(20) PRIMARY KEY,
    ID_DISTRITO_DEPTO INT NOT NULL,
    ID_DISTRITO_MUNICIPIO INT NOT NULL,
    ID_DISTRITO_ID INT NOT NULL,
    NOMBRE_EMPRESA VARCHAR(150) UNIQUE,
    CONTACTO_DIRECTO VARCHAR(100),
    FOREIGN KEY (ID_DISTRITO_DEPTO, ID_DISTRITO_MUNICIPIO, ID_DISTRITO_ID) REFERENCES DISTRITO(ID_DEPARTAMENTO, ID_MUNICIPIO, ID_DISTRITO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3.3 Tablas con FK a 3.2 (3)

CREATE TABLE POSTULANTE (
    ID_POSTULANTE VARCHAR(20) PRIMARY KEY,
    ID_GENERO INT NOT NULL,
    ID_TIPO_DOCUMENTO INT NOT NULL,
    NUM_DOCUMENTO VARCHAR(20) UNIQUE,
    ID_GRADO_ACADEMICO INT NOT NULL,
    ID_DISTRITO_DEPTO INT,
    ID_DISTRITO_MUNICIPIO INT,
    ID_DISTRITO_ID INT,
    NOMBRE VARCHAR(100),
    APELLIDO VARCHAR(100),
    FECHA_NACIMIENTO DATE,
    NUP VARCHAR(20) UNIQUE,
    DIRECCION_DETALLE VARCHAR(250),
    TELEFONO_CASA VARCHAR(15),
    TELEFONO_CELULAR VARCHAR(15),
    EMAIL VARCHAR(100) UNIQUE COLLATE utf8mb4_unicode_ci,
    FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID_GENERO),
    FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES TIPO_DOCUMENTO(ID_TIPO_DOCUMENTO),
    FOREIGN KEY (ID_GRADO_ACADEMICO) REFERENCES GRADO_ACADEMICO(ID_GRADO_ACADEMICO),
    FOREIGN KEY (ID_DISTRITO_DEPTO, ID_DISTRITO_MUNICIPIO, ID_DISTRITO_ID) REFERENCES DISTRITO(ID_DEPARTAMENTO, ID_MUNICIPIO, ID_DISTRITO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE OFERTA_ACADEMICA (
    ID_OFERTA_ACADEMICA VARCHAR(10) PRIMARY KEY,
    ID_GRADO_ACADEMICO INT,
    ID_INSTITUCION VARCHAR(20),
    FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION(ID_INSTITUCION),
    FOREIGN KEY (ID_GRADO_ACADEMICO) REFERENCES GRADO_ACADEMICO(ID_GRADO_ACADEMICO),
    UNIQUE (ID_INSTITUCION, ID_GRADO_ACADEMICO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE OFERTA_TRABAJO (
    NIT VARCHAR(20) NOT NULL,
    ID_OFERTA VARCHAR(10) NOT NULL,
    ID_GRADO_ACADEMICO INT,
    TITULO_PUESTO VARCHAR(150),
    FECHA_PUBLICACION DATE,
    FECHA_CADUCIDAD DATE,
    EXPERIENCIA_ANIOS INT,
    EDAD_MINIMA INT,
    EDAD_MAXIMA INT,
    DESCRIPCION_OFERTA_TRABAJO VARCHAR(5000),
    PRIMARY KEY (NIT, ID_OFERTA),
    FOREIGN KEY (NIT) REFERENCES EMPRESA(NIT),
    FOREIGN KEY (ID_GRADO_ACADEMICO) REFERENCES GRADO_ACADEMICO(ID_GRADO_ACADEMICO),
    UNIQUE (NIT, TITULO_PUESTO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3.4 Tablas con FK a 3.3 (7)

CREATE TABLE DETALLE_REQUISITO (
    NIT VARCHAR(20) NOT NULL,
    ID_OFERTA VARCHAR(10) NOT NULL,
    ID_DETALLE VARCHAR(10) NOT NULL,
    DESCRIPCION_REQUISITO VARCHAR(100),
    PRIMARY KEY (NIT, ID_OFERTA, ID_DETALLE),
    FOREIGN KEY (NIT, ID_OFERTA) REFERENCES OFERTA_TRABAJO(NIT, ID_OFERTA),
    UNIQUE (NIT, ID_OFERTA, DESCRIPCION_REQUISITO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE EXPERIENCIA_LABORAL (
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    NIT VARCHAR(20) NOT NULL,
    ID_EXPERIENCIA VARCHAR(10) NOT NULL,
    PUESTO_TRABAJO VARCHAR(100),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    DESCP_EXPERIENCIA_LABORAL VARCHAR(500),
    CONTACTO_REFERENCIA VARCHAR(100),
    PRIMARY KEY (ID_POSTULANTE, NIT, ID_EXPERIENCIA),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE(ID_POSTULANTE),
    FOREIGN KEY (NIT) REFERENCES EMPRESA(NIT),
    UNIQUE (ID_POSTULANTE, NIT, PUESTO_TRABAJO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE CERTIFICACION (
    ID_CERTIFICACION VARCHAR(10) NOT NULL,
    ID_INSTITUCION VARCHAR(20) NOT NULL,
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    ID_TIPO_CERTIFICACION INT,
    NOMBRE_CERTIFICACION VARCHAR(150),
    FECHA_CERTIFICACION DATE,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    PRIMARY KEY (ID_CERTIFICACION, ID_INSTITUCION, ID_POSTULANTE),
    FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION(ID_INSTITUCION),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE(ID_POSTULANTE),
    FOREIGN KEY (ID_TIPO_CERTIFICACION) REFERENCES TIPO_CERTIFICACION(ID_TIPO_CERTIFICACION),
    UNIQUE (ID_POSTULANTE, NOMBRE_CERTIFICACION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE FORMACION_ACADEMICA (
    ID_FORMACION VARCHAR(10) NOT NULL,
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    ID_OFERTA_ACADEMICA VARCHAR(10),
    TITULO_OBTENIDO VARCHAR(150),
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    FECHA_OBTENCION DATE,
    PRIMARY KEY (ID_FORMACION, ID_POSTULANTE),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE(ID_POSTULANTE),
    FOREIGN KEY (ID_OFERTA_ACADEMICA) REFERENCES OFERTA_ACADEMICA(ID_OFERTA_ACADEMICA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE HABILIDAD_POSTULANTE (
    ID_CATEGORIA_HABILIDAD INT NOT NULL,
    ID_HABILIDAD VARCHAR(10) NOT NULL,
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    NIVEL_DESTREZA VARCHAR(12),
    PRIMARY KEY (ID_CATEGORIA_HABILIDAD, ID_HABILIDAD, ID_POSTULANTE),
    FOREIGN KEY (ID_CATEGORIA_HABILIDAD, ID_HABILIDAD) REFERENCES HABILIDAD(ID_CATEGORIA_HABILIDAD, ID_HABILIDAD),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE(ID_POSTULANTE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE POSTULACION (
    ID_POSTULACION VARCHAR(10) NOT NULL,
    NIT VARCHAR(20) NOT NULL,
    ID_OFERTA VARCHAR(10) NOT NULL,
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    FECHA_APLICACION DATE,
    ESTADO_PROCESO VARCHAR(50),
    PRIMARY KEY (ID_POSTULACION),
    FOREIGN KEY (NIT, ID_OFERTA) REFERENCES OFERTA_TRABAJO(NIT, ID_OFERTA),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE(ID_POSTULANTE),
    UNIQUE (ID_POSTULANTE, NIT, ID_OFERTA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE RED_SOCIAL_POSTULANTE (
    ID_POSTULANTE VARCHAR(20) NOT NULL,
    ID_RED_SOCIAL INT NOT NULL,
    URL_PERFIL VARCHAR(100),
    PRIMARY KEY (ID_POSTULANTE, ID_RED_SOCIAL),
    FOREIGN KEY (ID_POSTULANTE) REFERENCES POSTULANTE(ID_POSTULANTE),
    FOREIGN KEY (ID_RED_SOCIAL) REFERENCES RED_SOCIAL(ID_RED_SOCIAL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- 4. INDICES (21)
-- ============================================================

CREATE INDEX IDX_MUNICIPIO_DEPTO ON MUNICIPIO (ID_DEPARTAMENTO);
CREATE INDEX IDX_DISTRITO_MUNICIPIO ON DISTRITO (ID_DEPARTAMENTO, ID_MUNICIPIO);
CREATE INDEX IDX_HABILIDAD_CATEGORIA ON HABILIDAD (ID_CATEGORIA_HABILIDAD);
CREATE INDEX IDX_EMPRESA_DISTRITO ON EMPRESA (ID_DISTRITO_DEPTO, ID_DISTRITO_MUNICIPIO, ID_DISTRITO_ID);
CREATE INDEX IDX_POSTULANTE_GENERO ON POSTULANTE (ID_GENERO);
CREATE INDEX IDX_POSTULANTE_TIPO_DOC ON POSTULANTE (ID_TIPO_DOCUMENTO);
CREATE INDEX IDX_POSTULANTE_DISTRITO ON POSTULANTE (ID_DISTRITO_DEPTO, ID_DISTRITO_MUNICIPIO, ID_DISTRITO_ID);
CREATE INDEX IDX_OFERTA_GRADO ON OFERTA_TRABAJO (ID_GRADO_ACADEMICO);
CREATE INDEX IDX_DETALLE_OFERTA ON DETALLE_REQUISITO (NIT, ID_OFERTA);
CREATE INDEX IDX_EXP_POSTULANTE ON EXPERIENCIA_LABORAL (ID_POSTULANTE);
CREATE INDEX IDX_EXP_EMPRESA ON EXPERIENCIA_LABORAL (NIT);
CREATE INDEX IDX_CERT_POSTULANTE ON CERTIFICACION (ID_POSTULANTE);
CREATE INDEX IDX_CERT_INSTITUCION ON CERTIFICACION (ID_INSTITUCION);
CREATE INDEX IDX_FORM_POSTULANTE ON FORMACION_ACADEMICA (ID_POSTULANTE);
CREATE INDEX IDX_HAB_POST_POSTULANTE ON HABILIDAD_POSTULANTE (ID_POSTULANTE);
CREATE INDEX IDX_HAB_POST_HABILIDAD ON HABILIDAD_POSTULANTE (ID_HABILIDAD);
CREATE INDEX IDX_POSTULACION_POSTULANTE ON POSTULACION (ID_POSTULANTE);
CREATE INDEX IDX_POSTULACION_OFERTA ON POSTULACION (NIT, ID_OFERTA);
CREATE INDEX IDX_RED_POST_POSTULANTE ON RED_SOCIAL_POSTULANTE (ID_POSTULANTE);
CREATE INDEX IDX_OA_INSTITUCION ON OFERTA_ACADEMICA (ID_INSTITUCION);
CREATE INDEX IDX_OA_GRADO ON OFERTA_ACADEMICA (ID_GRADO_ACADEMICO);

-- ============================================================
