-- ============================================================
-- ESQUEMA BOLSA DE TRABAJO - 27 TRIGGERS
-- Compatible con InfinityFree (phpMyAdmin)
-- ============================================================
-- INSTRUCCIONES:
-- 1. Ejecuta PRIMERO esquema_tablas.sql (Delimitador: ;)
-- 2. Luego en phpMyAdmin > pestaña SQL
-- 3. Cambia el Delimitador a: $$
-- 4. Pega este archivo y ejecuta
-- 5. Vuelve a dejar el Delimitador en: ;
-- ============================================================

-- ============================================================
-- DROP TRIGGERS (27) - todos con $$ por el delimitador
-- ============================================================

DROP TRIGGER IF EXISTS TR_POSTULANTE_EDAD$$
DROP TRIGGER IF EXISTS TR_POSTULANTE_EDAD_UPD$$
DROP TRIGGER IF EXISTS TR_POSTULANTE_GRADO$$
DROP TRIGGER IF EXISTS TR_POSTULANTE_GRADO_UPD$$
DROP TRIGGER IF EXISTS TR_OFERTA_RANGO_EDAD$$
DROP TRIGGER IF EXISTS TR_OFERTA_RANGO_EDAD_UPD$$
DROP TRIGGER IF EXISTS TR_OFERTA_VIGENCIA$$
DROP TRIGGER IF EXISTS TR_OFERTA_VIGENCIA_UPD$$
DROP TRIGGER IF EXISTS TR_POSTULACION_VIGENCIA$$
DROP TRIGGER IF EXISTS TR_EXP_LABORAL_FECHAS$$
DROP TRIGGER IF EXISTS TR_EXP_LABORAL_FECHAS_UPD$$
DROP TRIGGER IF EXISTS TR_CERTIFICACION_FECHAS$$
DROP TRIGGER IF EXISTS TR_CERTIFICACION_FECHAS_UPD$$
DROP TRIGGER IF EXISTS TR_FORMACION_FECHAS$$
DROP TRIGGER IF EXISTS TR_FORMACION_FECHAS_UPD$$
DROP TRIGGER IF EXISTS TR_HABILIDAD_NIVEL$$
DROP TRIGGER IF EXISTS TR_HABILIDAD_NIVEL_UPD$$
DROP TRIGGER IF EXISTS TR_MUNICIPIO_DEPTO$$
DROP TRIGGER IF EXISTS TR_MUNICIPIO_DEPTO_UPD$$
DROP TRIGGER IF EXISTS TR_DISTRITO_MUNICIPIO$$
DROP TRIGGER IF EXISTS TR_DISTRITO_MUNICIPIO_UPD$$
DROP TRIGGER IF EXISTS TR_HABILIDAD_CATEGORIA$$
DROP TRIGGER IF EXISTS TR_HABILIDAD_CATEGORIA_UPD$$
DROP TRIGGER IF EXISTS TR_EMPRESA_DISTRITO$$
DROP TRIGGER IF EXISTS TR_EMPRESA_DISTRITO_UPD$$
DROP TRIGGER IF EXISTS TR_POSTULANTE_FK$$
DROP TRIGGER IF EXISTS TR_POSTULANTE_FK_UPD$$

-- ============================================================
-- 5. TRIGGERS SEMANTICOS (9 grupos = 17 triggers)
-- ============================================================

-- 5.1 TR_POSTULANTE_EDAD (INSERT + UPDATE)

CREATE TRIGGER TR_POSTULANTE_EDAD BEFORE INSERT ON POSTULANTE
FOR EACH ROW
BEGIN
    IF NEW.FECHA_NACIMIENTO > CURDATE() THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'La fecha de nacimiento no puede ser futura';
    END IF;
    IF DATE_ADD(NEW.FECHA_NACIMIENTO, INTERVAL 18 YEAR) > CURDATE() THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El postulante debe ser mayor de edad';
    END IF;
END$$

CREATE TRIGGER TR_POSTULANTE_EDAD_UPD BEFORE UPDATE ON POSTULANTE
FOR EACH ROW
BEGIN
    IF NEW.FECHA_NACIMIENTO > CURDATE() THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'La fecha de nacimiento no puede ser futura';
    END IF;
    IF DATE_ADD(NEW.FECHA_NACIMIENTO, INTERVAL 18 YEAR) > CURDATE() THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El postulante debe ser mayor de edad';
    END IF;
END$$

-- 5.2 TR_POSTULANTE_GRADO (INSERT + UPDATE)

CREATE TRIGGER TR_POSTULANTE_GRADO BEFORE INSERT ON POSTULANTE
FOR EACH ROW
BEGIN
    IF (SELECT LOWER(NOMBRE_GRADO) FROM GRADO_ACADEMICO WHERE ID_GRADO_ACADEMICO = NEW.ID_GRADO_ACADEMICO) IN ('bachiller') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El postulante debe tener un grado academico superior a Bachiller';
    END IF;
END$$

CREATE TRIGGER TR_POSTULANTE_GRADO_UPD BEFORE UPDATE ON POSTULANTE
FOR EACH ROW
BEGIN
    IF (SELECT LOWER(NOMBRE_GRADO) FROM GRADO_ACADEMICO WHERE ID_GRADO_ACADEMICO = NEW.ID_GRADO_ACADEMICO) IN ('bachiller') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El postulante debe tener un grado academico superior a Bachiller';
    END IF;
END$$

-- 5.3 TR_OFERTA_RANGO_EDAD (INSERT + UPDATE)

CREATE TRIGGER TR_OFERTA_RANGO_EDAD BEFORE INSERT ON OFERTA_TRABAJO
FOR EACH ROW
BEGIN
    IF NEW.EDAD_MINIMA < 18 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Edad minima debe ser mayor o igual a 18';
    END IF;
    IF NEW.EDAD_MINIMA > NEW.EDAD_MAXIMA THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Edad minima no puede ser mayor a la maxima';
    END IF;
END$$

CREATE TRIGGER TR_OFERTA_RANGO_EDAD_UPD BEFORE UPDATE ON OFERTA_TRABAJO
FOR EACH ROW
BEGIN
    IF NEW.EDAD_MINIMA < 18 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Edad minima debe ser mayor o igual a 18';
    END IF;
    IF NEW.EDAD_MINIMA > NEW.EDAD_MAXIMA THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Edad minima no puede ser mayor a la maxima';
    END IF;
END$$

-- 5.4 TR_OFERTA_VIGENCIA (INSERT + UPDATE)

CREATE TRIGGER TR_OFERTA_VIGENCIA BEFORE INSERT ON OFERTA_TRABAJO
FOR EACH ROW
BEGIN
    IF NEW.FECHA_CADUCIDAD <= NEW.FECHA_PUBLICACION THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'La oferta ya caduco o fecha invalida';
    END IF;
END$$

CREATE TRIGGER TR_OFERTA_VIGENCIA_UPD BEFORE UPDATE ON OFERTA_TRABAJO
FOR EACH ROW
BEGIN
    IF NEW.FECHA_CADUCIDAD <= NEW.FECHA_PUBLICACION THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'La oferta ya caduco o fecha invalida';
    END IF;
END$$

-- 5.5 TR_POSTULACION_VIGENCIA (INSERT solo)

CREATE TRIGGER TR_POSTULACION_VIGENCIA BEFORE INSERT ON POSTULACION
FOR EACH ROW
BEGIN
    IF (SELECT FECHA_CADUCIDAD FROM OFERTA_TRABAJO WHERE NIT = NEW.NIT AND ID_OFERTA = NEW.ID_OFERTA) < CURDATE() THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'La oferta de trabajo ha vencido';
    END IF;
END$$

-- 5.6 TR_EXP_LABORAL_FECHAS (INSERT + UPDATE)

CREATE TRIGGER TR_EXP_LABORAL_FECHAS BEFORE INSERT ON EXPERIENCIA_LABORAL
FOR EACH ROW
BEGIN
    IF NEW.FECHA_INICIO >= NEW.FECHA_FIN THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha inicio debe ser menor a fecha fin';
    END IF;
END$$

CREATE TRIGGER TR_EXP_LABORAL_FECHAS_UPD BEFORE UPDATE ON EXPERIENCIA_LABORAL
FOR EACH ROW
BEGIN
    IF NEW.FECHA_INICIO >= NEW.FECHA_FIN THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha inicio debe ser menor a fecha fin';
    END IF;
END$$

-- 5.7 TR_CERTIFICACION_FECHAS (INSERT + UPDATE)

CREATE TRIGGER TR_CERTIFICACION_FECHAS BEFORE INSERT ON CERTIFICACION
FOR EACH ROW
BEGIN
    IF NEW.FECHA_INICIO >= NEW.FECHA_FIN THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha inicio debe ser menor a fecha fin';
    END IF;
    IF NEW.FECHA_INICIO > CURDATE() THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha inicio no puede ser una fecha futura';
    END IF;
    IF NEW.FECHA_FIN > CURDATE() THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha fin no puede ser una fecha futura';
    END IF;
    IF NEW.FECHA_CERTIFICACION < NEW.FECHA_FIN THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de certificacion no puede ser menor a la fecha fin del periodo';
    END IF;
    IF NEW.FECHA_CERTIFICACION > DATE_ADD(NEW.FECHA_FIN, INTERVAL 1 YEAR) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de certificacion no puede exceder un año despues de la fecha fin del periodo';
    END IF;
    IF NEW.FECHA_CERTIFICACION > CURDATE() THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de certificacion no puede ser una fecha futura';
    END IF;
END$$

CREATE TRIGGER TR_CERTIFICACION_FECHAS_UPD BEFORE UPDATE ON CERTIFICACION
FOR EACH ROW
BEGIN
    IF NEW.FECHA_INICIO >= NEW.FECHA_FIN THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha inicio debe ser menor a fecha fin';
    END IF;
    IF NEW.FECHA_INICIO > CURDATE() THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha inicio no puede ser una fecha futura';
    END IF;
    IF NEW.FECHA_FIN > CURDATE() THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha fin no puede ser una fecha futura';
    END IF;
    IF NEW.FECHA_CERTIFICACION < NEW.FECHA_FIN THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de certificacion no puede ser menor a la fecha fin del periodo';
    END IF;
    IF NEW.FECHA_CERTIFICACION > DATE_ADD(NEW.FECHA_FIN, INTERVAL 1 YEAR) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de certificacion no puede exceder un año despues de la fecha fin del periodo';
    END IF;
    IF NEW.FECHA_CERTIFICACION > CURDATE() THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de certificacion no puede ser una fecha futura';
    END IF;
END$$

-- 5.8 TR_FORMACION_FECHAS (INSERT + UPDATE)

CREATE TRIGGER TR_FORMACION_FECHAS BEFORE INSERT ON FORMACION_ACADEMICA
FOR EACH ROW
BEGIN
    IF NEW.FECHA_INICIO >= NEW.FECHA_FIN THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha inicio debe ser menor a fecha fin';
    END IF;
    IF NEW.FECHA_INICIO > CURDATE() THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha inicio no puede ser una fecha futura';
    END IF;
    IF NEW.FECHA_FIN > CURDATE() THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha fin no puede ser una fecha futura';
    END IF;
    IF NEW.FECHA_OBTENCION < NEW.FECHA_FIN THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de obtencion no puede ser menor a la fecha fin del periodo';
    END IF;
    IF NEW.FECHA_OBTENCION > DATE_ADD(NEW.FECHA_FIN, INTERVAL 1 YEAR) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de obtencion no puede exceder un año despues de la fecha fin del periodo';
    END IF;
    IF NEW.FECHA_OBTENCION > CURDATE() THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de obtencion no puede ser una fecha futura';
    END IF;
END$$

CREATE TRIGGER TR_FORMACION_FECHAS_UPD BEFORE UPDATE ON FORMACION_ACADEMICA
FOR EACH ROW
BEGIN
    IF NEW.FECHA_INICIO >= NEW.FECHA_FIN THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha inicio debe ser menor a fecha fin';
    END IF;
    IF NEW.FECHA_INICIO > CURDATE() THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha inicio no puede ser una fecha futura';
    END IF;
    IF NEW.FECHA_FIN > CURDATE() THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha fin no puede ser una fecha futura';
    END IF;
    IF NEW.FECHA_OBTENCION < NEW.FECHA_FIN THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de obtencion no puede ser menor a la fecha fin del periodo';
    END IF;
    IF NEW.FECHA_OBTENCION > DATE_ADD(NEW.FECHA_FIN, INTERVAL 1 YEAR) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de obtencion no puede exceder un año despues de la fecha fin del periodo';
    END IF;
    IF NEW.FECHA_OBTENCION > CURDATE() THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Fecha de obtencion no puede ser una fecha futura';
    END IF;
END$$

-- 5.9 TR_HABILIDAD_NIVEL (INSERT + UPDATE)

CREATE TRIGGER TR_HABILIDAD_NIVEL BEFORE INSERT ON HABILIDAD_POSTULANTE
FOR EACH ROW
BEGIN
    IF NEW.NIVEL_DESTREZA NOT IN ('Básico', 'Intermedio', 'Avanzado') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Nivel de destreza debe ser Basico, Intermedio o Avanzado';
    END IF;
END$$

CREATE TRIGGER TR_HABILIDAD_NIVEL_UPD BEFORE UPDATE ON HABILIDAD_POSTULANTE
FOR EACH ROW
BEGIN
    IF NEW.NIVEL_DESTREZA NOT IN ('Básico', 'Intermedio', 'Avanzado') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Nivel de destreza debe ser Basico, Intermedio o Avanzado';
    END IF;
END$$

-- ============================================================
-- 6. TRIGGERS DE INTEGRIDAD REFERENCIAL (5 grupos = 10 triggers)
-- ============================================================

-- 6.1 TR_MUNICIPIO_DEPTO (INSERT + UPDATE)

CREATE TRIGGER TR_MUNICIPIO_DEPTO BEFORE INSERT ON MUNICIPIO
FOR EACH ROW
BEGIN
    IF (SELECT 1 FROM DEPARTAMENTO WHERE ID_DEPARTAMENTO = NEW.ID_DEPARTAMENTO) IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El departamento asociado no existe';
    END IF;
END$$

CREATE TRIGGER TR_MUNICIPIO_DEPTO_UPD BEFORE UPDATE ON MUNICIPIO
FOR EACH ROW
BEGIN
    IF (SELECT 1 FROM DEPARTAMENTO WHERE ID_DEPARTAMENTO = NEW.ID_DEPARTAMENTO) IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El departamento asociado no existe';
    END IF;
END$$

-- 6.2 TR_DISTRITO_MUNICIPIO (INSERT + UPDATE)

CREATE TRIGGER TR_DISTRITO_MUNICIPIO BEFORE INSERT ON DISTRITO
FOR EACH ROW
BEGIN
    IF (SELECT 1 FROM MUNICIPIO WHERE ID_DEPARTAMENTO = NEW.ID_DEPARTAMENTO AND ID_MUNICIPIO = NEW.ID_MUNICIPIO) IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El municipio asociado no existe';
    END IF;
END$$

CREATE TRIGGER TR_DISTRITO_MUNICIPIO_UPD BEFORE UPDATE ON DISTRITO
FOR EACH ROW
BEGIN
    IF (SELECT 1 FROM MUNICIPIO WHERE ID_DEPARTAMENTO = NEW.ID_DEPARTAMENTO AND ID_MUNICIPIO = NEW.ID_MUNICIPIO) IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El municipio asociado no existe';
    END IF;
END$$

-- 6.3 TR_HABILIDAD_CATEGORIA (INSERT + UPDATE)

CREATE TRIGGER TR_HABILIDAD_CATEGORIA BEFORE INSERT ON HABILIDAD
FOR EACH ROW
BEGIN
    IF (SELECT 1 FROM CATEGORIA_HABILIDAD WHERE ID_CATEGORIA_HABILIDAD = NEW.ID_CATEGORIA_HABILIDAD) IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'La categoria asociada no existe';
    END IF;
END$$

CREATE TRIGGER TR_HABILIDAD_CATEGORIA_UPD BEFORE UPDATE ON HABILIDAD
FOR EACH ROW
BEGIN
    IF (SELECT 1 FROM CATEGORIA_HABILIDAD WHERE ID_CATEGORIA_HABILIDAD = NEW.ID_CATEGORIA_HABILIDAD) IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'La categoria asociada no existe';
    END IF;
END$$

-- 6.4 TR_EMPRESA_DISTRITO (INSERT + UPDATE)

CREATE TRIGGER TR_EMPRESA_DISTRITO BEFORE INSERT ON EMPRESA
FOR EACH ROW
BEGIN
    IF (SELECT 1 FROM DISTRITO WHERE ID_DEPARTAMENTO = NEW.ID_DISTRITO_DEPTO AND ID_MUNICIPIO = NEW.ID_DISTRITO_MUNICIPIO AND ID_DISTRITO = NEW.ID_DISTRITO_ID) IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El distrito asociado no existe';
    END IF;
END$$

CREATE TRIGGER TR_EMPRESA_DISTRITO_UPD BEFORE UPDATE ON EMPRESA
FOR EACH ROW
BEGIN
    IF (SELECT 1 FROM DISTRITO WHERE ID_DEPARTAMENTO = NEW.ID_DISTRITO_DEPTO AND ID_MUNICIPIO = NEW.ID_DISTRITO_MUNICIPIO AND ID_DISTRITO = NEW.ID_DISTRITO_ID) IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El distrito asociado no existe';
    END IF;
END$$

-- 6.5 TR_POSTULANTE_FK (INSERT + UPDATE)

CREATE TRIGGER TR_POSTULANTE_FK BEFORE INSERT ON POSTULANTE
FOR EACH ROW
BEGIN
    IF (SELECT 1 FROM GENERO WHERE ID_GENERO = NEW.ID_GENERO) IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El genero asociado no existe';
    END IF;
    IF (SELECT 1 FROM TIPO_DOCUMENTO WHERE ID_TIPO_DOCUMENTO = NEW.ID_TIPO_DOCUMENTO) IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El tipo de documento asociado no existe';
    END IF;
    IF NEW.ID_GRADO_ACADEMICO IS NOT NULL AND (SELECT 1 FROM GRADO_ACADEMICO WHERE ID_GRADO_ACADEMICO = NEW.ID_GRADO_ACADEMICO) IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El grado academico asociado no existe';
    END IF;
END$$

CREATE TRIGGER TR_POSTULANTE_FK_UPD BEFORE UPDATE ON POSTULANTE
FOR EACH ROW
BEGIN
    IF (SELECT 1 FROM GENERO WHERE ID_GENERO = NEW.ID_GENERO) IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El genero asociado no existe';
    END IF;
    IF (SELECT 1 FROM TIPO_DOCUMENTO WHERE ID_TIPO_DOCUMENTO = NEW.ID_TIPO_DOCUMENTO) IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El tipo de documento asociado no existe';
    END IF;
    IF NEW.ID_GRADO_ACADEMICO IS NOT NULL AND (SELECT 1 FROM GRADO_ACADEMICO WHERE ID_GRADO_ACADEMICO = NEW.ID_GRADO_ACADEMICO) IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El grado academico asociado no existe';
    END IF;
END$$

-- Volver a delimiter por defecto
DELIMITER ;
