import sqlite3

conn = sqlite3.connect('C:/Users/Gissi Giron/AndroidStudioProjects/BT/app/src/main/assets/si.db')
cur = conn.cursor()

triggers = [
('TR_NIVEL_EDUCATIVO', '''CREATE TRIGGER TR_NIVEL_EDUCATIVO
BEFORE INSERT ON FORMACION_ACADEMICA
FOR EACH ROW
BEGIN
    SELECT RAISE(ABORT, 'El sistema no permite registros con nivel de bachillerato o inferior.')
    WHERE (SELECT UPPER(NOMBRE_GRADO) FROM GRADO_ACADEMICO WHERE ID_GRADO_ACADEMICO = NEW.ID_GRADO_ACADEMICO) 
    IN ('BACHILLERATO', 'EDUCACIÓN BÁSICA', 'PRIMARIA');
END'''),

('TR_POSTULACION_UNICA', '''CREATE TRIGGER TR_POSTULACION_UNICA
BEFORE INSERT ON POSTULACION
FOR EACH ROW
BEGIN
    SELECT RAISE(ABORT, 'Ya existe una postulación activa para esta oferta.')
    WHERE (SELECT COUNT(*) FROM POSTULACION WHERE ID_POSTULANTE = NEW.ID_POSTULANTE AND ID_OFERTA = NEW.ID_OFERTA) > 0;
END'''),

('TR_EXP_LABORAL_FECHAS', '''CREATE TRIGGER TR_EXP_LABORAL_FECHAS
BEFORE INSERT ON EXPERIENCIA_LABORAL
FOR EACH ROW
BEGIN
    SELECT RAISE(ABORT, 'La fecha de inicio debe ser anterior a la fecha de fin.')
    WHERE NEW.FECHA_INICIO >= NEW.FECHA_FIN;
END'''),

('TR_OFERTA_RANGO_EDAD', '''CREATE TRIGGER TR_OFERTA_RANGO_EDAD
BEFORE INSERT ON OFERTA_TRABAJO
FOR EACH ROW
BEGIN
    SELECT RAISE(ABORT, 'La edad mínima no puede ser mayor a la edad máxima.')
    WHERE NEW.EDAD_MINIMA > NEW.EDAD_MAXIMA;
END'''),

('TR_OFERTA_VIGENCIA', '''CREATE TRIGGER TR_OFERTA_VIGENCIA
BEFORE INSERT ON OFERTA_TRABAJO
FOR EACH ROW
BEGIN
    SELECT RAISE(ABORT, 'La fecha de caducidad debe ser posterior a la fecha de publicación.')
    WHERE NEW.FECHA_CADUCIDAD < NEW.FECHA_PUBLICACION;
END'''),

('TR_CERTIFICACION_CODIGO', '''CREATE TRIGGER TR_CERTIFICACION_CODIGO
BEFORE INSERT ON CERTIFICACION
FOR EACH ROW
BEGIN
    SELECT RAISE(ABORT, 'Este código de certificación ya ha sido registrado.')
    WHERE (SELECT COUNT(*) FROM CERTIFICACION WHERE ID_POSTULANTE = NEW.ID_POSTULANTE AND CODIGO_CERTIFICACION = NEW.CODIGO_CERTIFICACION) > 0;
END'''),

('TR_MUNICIPIO_DEPTO', '''CREATE TRIGGER TR_MUNICIPIO_DEPTO
BEFORE INSERT ON MUNICIPIO
FOR EACH ROW
BEGIN
    SELECT RAISE(ABORT, 'Error de integridad: El departamento asociado no existe.')
    WHERE (SELECT COUNT(*) FROM DEPARTAMENTO WHERE ID_DEPARTAMENTO = NEW.ID_DEPARTAMENTO) = 0;
END'''),

('TR_PROTEC_CATEGORIA', '''CREATE TRIGGER TR_PROTEC_CATEGORIA
BEFORE DELETE ON CATEGORIA_HABILIDAD
FOR EACH ROW
BEGIN
    SELECT RAISE(ABORT, 'Esta categoría tiene habilidades vinculadas.')
    WHERE (SELECT COUNT(*) FROM HABILIDAD WHERE ID_CATEGORIA_HABILIDAD = OLD.ID_CATEGORIA_HABILIDAD) > 0;
END'''),

('TR_PROTEC_DISTRITO', '''CREATE TRIGGER TR_PROTEC_DISTRITO
BEFORE DELETE ON DISTRITO
FOR EACH ROW
BEGIN
    SELECT RAISE(ABORT, 'Existen postulantes o empresas asociados a este distrito.')
    WHERE (SELECT COUNT(*) FROM POSTULANTE WHERE ID_DISTRITO = OLD.ID_DISTRITO) > 0
       OR (SELECT COUNT(*) FROM EMPRESA WHERE ID_DISTRITO = OLD.ID_DISTRITO) > 0;
END'''),

('TR_PROTEC_GRADO', '''CREATE TRIGGER TR_PROTEC_GRADO
BEFORE DELETE ON GRADO_ACADEMICO
FOR EACH ROW
BEGIN
    SELECT RAISE(ABORT, 'Este grado está siendo solicitado en ofertas de trabajo.')
    WHERE (SELECT COUNT(*) FROM OFERTA_TRABAJO WHERE ID_GRADO_ACADEMICO = OLD.ID_GRADO_ACADEMICO) > 0;
END'''),

('TR_PROTEC_INSTITUCION', '''CREATE TRIGGER TR_PROTEC_INSTITUCION
BEFORE DELETE ON INSTITUCION
FOR EACH ROW
BEGIN
    SELECT RAISE(ABORT, 'La institución posee ofertas académicas o certificaciones.')
    WHERE (SELECT COUNT(*) FROM OFERTA_ACADEMICA WHERE ID_INSTITUCION = OLD.ID_INSTITUCION) > 0;
END'''),

('TR_PROTEC_TIPO_DOC', '''CREATE TRIGGER TR_PROTEC_TIPO_DOC
BEFORE DELETE ON TIPO_DOCUMENTO
FOR EACH ROW
BEGIN
    SELECT RAISE(ABORT, 'Hay postulantes registrados con este tipo de documento.')
    WHERE (SELECT COUNT(*) FROM POSTULANTE WHERE ID_TIPO_DOCUMENTO = OLD.ID_TIPO_DOCUMENTO) > 0;
END'''),

('TR_CASCADA_USUARIO', '''CREATE TRIGGER TR_CASCADA_USUARIO
AFTER DELETE ON POSTULANTE
FOR EACH ROW
BEGIN
    DELETE FROM USUARIO WHERE ID_POSTULANTE = OLD.ID_POSTULANTE;
END'''),

('TR_CASCADA_REDES', '''CREATE TRIGGER TR_CASCADA_REDES
AFTER DELETE ON POSTULANTE
FOR EACH ROW
BEGIN
    DELETE FROM RED_SOCIAL_POSTULANTE WHERE ID_POSTULANTE = OLD.ID_POSTULANTE;
END'''),

('TR_CASCADA_REQUISITOS', '''CREATE TRIGGER TR_CASCADA_REQUISITOS
AFTER DELETE ON OFERTA_TRABAJO
FOR EACH ROW
BEGIN
    DELETE FROM DETALLE_REQUISITO WHERE ID_EMPRESA = OLD.ID_EMPRESA AND ID_OFERTA = OLD.ID_OFERTA;
END'''),

('TR_CASCADA_HABILIDADES', '''CREATE TRIGGER TR_CASCADA_HABILIDADES
AFTER DELETE ON POSTULANTE
FOR EACH ROW
BEGIN
    DELETE FROM HABILIDAD_POSTULANTE WHERE ID_POSTULANTE = OLD.ID_POSTULANTE;
END'''),

('TR_USUARIO_FORMATO', '''CREATE TRIGGER TR_USUARIO_FORMATO
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN
    SELECT RAISE(ABORT, 'La contraseña debe tener al menos 8 caracteres.')
    WHERE LENGTH(NEW.PASSWORD) < 8;
END'''),

('TR_OFERTA_FECHA_AUTO', '''CREATE TRIGGER TR_OFERTA_FECHA_AUTO
BEFORE INSERT ON OFERTA_TRABAJO
FOR EACH ROW
WHEN NEW.FECHA_PUBLICACION IS NULL
BEGIN
    SELECT RAISE(ABORT, 'La fecha de publicación se asigna automáticamente.')
    WHERE NEW.FECHA_PUBLICACION IS NULL;
END'''),

('TR_HABILIDAD_NIVEL', '''CREATE TRIGGER TR_HABILIDAD_NIVEL
BEFORE INSERT ON HABILIDAD_POSTULANTE
FOR EACH ROW
BEGIN
    SELECT RAISE(ABORT, 'El nivel de destreza debe ser 1, 2 o 3.')
    WHERE NEW.NIVEL_DESTREZA NOT IN (1, 2, 3);
END'''),

('TR_EMPRESA_NOMBRE_UNICO', '''CREATE TRIGGER TR_EMPRESA_NOMBRE_UNICO
BEFORE INSERT ON EMPRESA
FOR EACH ROW
BEGIN
    SELECT RAISE(ABORT, 'Ya existe una empresa registrada con ese nombre.')
    WHERE (SELECT COUNT(*) FROM EMPRESA WHERE UPPER(NOMBRE_EMPRESA) = UPPER(NEW.NOMBRE_EMPRESA)) > 0;
END'''),
]

for name, sql in triggers:
    try:
        cur.execute(sql)
        print(f"OK: {name}")
    except Exception as e:
        print(f"Error {name}: {e}")

conn.commit()
cur.execute("SELECT name FROM sqlite_master WHERE type=?", ('trigger',))
print(f"\nTriggers recreados: {len(cur.fetchall())}")
conn.close()