INSERT INTO POSTULANTE (ID_POSTULANTE, ID_GENERO, ID_TIPO_DOCUMENTO, ID_DISTRITO_DEPTO, ID_DISTRITO_MUNICIPIO, ID_DISTRITO_ID, NOMBRE, APELLIDO, NUM_DOCUMENTO, EMAIL) 
VALUES ('GC05001', 1, 1, 1, 1, 1, 'Juan', 'Perez', '123456789', 'juan@test.com');
