package sv.ues.fia.eisi.bt.utils

import android.content.Context
import sv.ues.fia.eisi.bt.R

object TriggerErrorTranslator {

    private val ERROR_MAP = mapOf(
        "UNIQUE constraint failed" to R.string.error_unique_constraint,
        "FOREIGN KEY constraint failed" to R.string.error_foreign_key,
        "NOT NULL constraint failed" to R.string.error_not_null,
        "constraint failed" to R.string.error_constraint,
        "Duplicado: Ya existe un registro con esa clave" to R.string.error_duplicado_clave,
        "Ya existe un genero con ese nombre" to R.string.error_duplicado_genero,
        "Ya existe una categoria con ese nombre" to R.string.error_duplicado_categoria_habilidad,
        "Ya existe un tipo de documento con ese nombre" to R.string.error_duplicado_tipo_documento,
        "Ya existe un departamento con ese nombre" to R.string.error_duplicado_departamento,
        "Ya existe un grado academico con ese nombre" to R.string.error_duplicado_grado_academico,
        "Ya existe una red social con ese nombre" to R.string.error_duplicado_red_social,
        "Ya existe una institucion con ese nombre" to R.string.error_duplicado_institucion,
        "Ya existe un municipio con ese nombre " to R.string.error_duplicado_municipio,
        "Ya existe un distrito con ese nombre en el municipio" to R.string.error_duplicado_distrito,
        "Ya existe una habilidad con ese nombre" to R.string.error_duplicado_habilidad,
        "Ya existe una empresa con ese NIT" to R.string.error_duplicado_empresa_nit,
        "Ya existe una empresa con ese nombre" to R.string.error_duplicado_empresa_nombre,
        "Ya existe un postulante con ese documento" to R.string.error_duplicado_postulante_doc,
        "Ya existe un postulante con ese NUP" to R.string.error_duplicado_postulante_nup,
        "Ya existe un postulante con ese email" to R.string.error_duplicado_postulante_email,
        "Ya existe un usuario con ese nombre" to R.string.error_duplicado_usuario,
        "Ya existe una oferta con ese titulo en la empresa" to R.string.error_duplicado_oferta,
        "Ya existe un requisito con esa descripcion en la oferta" to R.string.error_duplicado_requisito,
        "Ya existe una experiencia con ese puesto para el postulante" to R.string.error_duplicado_experiencia,
        "Ya existe una formacion academica con ese titulo en el mismo periodo para el postulante" to R.string.error_duplicado_formacion_academica,
        "Ya existe una certificacion con ese codigo para el postulante" to R.string.error_duplicado_certificacion,
        "Ya existe una certificacion con ese nombre para el postulante" to R.string.error_duplicado_certificacion_nombre,
        "El postulante ya aplico a esta oferta" to R.string.error_postulante_ya_aplico,
        "La oferta de trabajo ha vencido" to R.string.error_oferta_vencida,
        "El postulante debe tener un grado academico superior a Bachiller" to R.string.error_grado_academico_insuficiente,
        "grado academico superior" to R.string.error_grado_academico_insuficiente,
        "La red social ya esta vinculada al postulante" to R.string.error_red_social_vinculada,
        "La habilidad ya esta asignada al postulante" to R.string.error_habilidad_asignada,
        "Ya existe una oferta academica para esa institucion y grado" to R.string.error_oferta_academica_duplicada,
        "Nivel academico insuficiente" to R.string.error_nivel_bachillerato,
        "nivel de bachillerato" to R.string.error_nivel_bachillerato,
        "Fecha inicio debe ser menor a fecha fin" to R.string.error_fecha_inicio_fin,
        "fecha de inicio" to R.string.error_fecha_inicio_fin,
        "Edad minima debe ser mayor o igual a 18" to R.string.error_edad_minima_18,
        "Edad minima no puede ser mayor a la maxima" to R.string.error_edad_minima_maxima,
        "edad minima" to R.string.error_edad_minima_maxima,
        "La oferta ya caduco o fecha invalida" to R.string.error_fecha_caducidad,
        "fecha de caducidad" to R.string.error_fecha_caducidad,
        "El departamento asociado no existe" to R.string.error_departamento_no_existe,
        "departamento" to R.string.error_comb_valores,
        "El municipio asociado no existe" to R.string.error_municipio_no_existe,
        "municipio" to R.string.error_municipio_no_valido,
        "La categoria asociada no existe" to R.string.error_categoria_no_existe,
        "categoria" to R.string.error_categoria_no_valida,
        "El distrito asociado no existe" to R.string.error_distrito_no_existe,
        "distrito" to R.string.error_distrito_no_valido,
        "El genero asociado no existe" to R.string.error_genero_no_existe,
        "genero" to R.string.error_genero_no_valido,
        "El tipo de documento asociado no existe" to R.string.error_tipo_doc_no_existe,
        "tipo de documento" to R.string.error_tipo_doc_no_valido,
        "Password minimo 8 caracteres" to R.string.error_password_minimo,
        "contrasena" to R.string.error_password_minimo,
        "Nivel de destreza debe ser 1, 2 o 3" to R.string.error_nivel_destreza,
        "nivel de destreza" to R.string.error_nivel_destreza_simple,
        "postulante debe ser mayor de edad" to R.string.error_mayor_edad,
        "mayor de edad" to R.string.error_mayor_edad,
        "Correo electronico no valido" to R.string.error_correo_invalido,
        "correo electronico" to R.string.error_correo_invalido,
        "fecha de nacimiento" to R.string.error_fecha_nacimiento,
        "fecha de certificacion no puede ser menor a la fecha fin" to R.string.error_fecha_cert_menor_fin,
        "fecha de certificacion no puede exceder un año" to R.string.error_fecha_cert_excede_anio,
        "fecha de certificacion no puede ser una fecha futura" to R.string.error_fecha_cert_futura,
        "fecha de obtencion no puede ser menor a la fecha fin" to R.string.error_fecha_obt_menor_fin,
        "fecha de obtencion no puede exceder un año" to R.string.error_fecha_obt_excede_anio,
        "fecha de obtencion no puede ser una fecha futura" to R.string.error_fecha_obt_futura,
        "fecha inicio no puede ser una fecha futura" to R.string.error_fecha_inicio_futura,
        "fecha fin no puede ser una fecha futura" to R.string.error_fecha_fin_futura,
        "No se puede eliminar: el departamento tiene municipios asociados" to R.string.error_eliminar_departamento,
        "No se puede eliminar: el municipio tiene distritos asociados" to R.string.error_eliminar_municipio,
        "No se puede eliminar: el distrito tiene postulantes asociados" to R.string.error_eliminar_distrito_postulante,
        "No se puede eliminar: el distrito tiene empresas asociadas" to R.string.error_eliminar_distrito_empresa,
        "No se puede eliminar: la categoria tiene habilidades asociadas" to R.string.error_eliminar_categoria,
        "No se puede eliminar: la habilidad esta asignada a postulantes" to R.string.error_eliminar_habilidad,
        "No se puede eliminar: el postulante tiene postulaciones" to R.string.error_eliminar_postulante_postulaciones,
        "No se puede eliminar: el postulante tiene experiencias laborales" to R.string.error_eliminar_postulante_experiencias,
        "No se puede eliminar: el postulante tiene formaciones academicas" to R.string.error_eliminar_postulante_formaciones,
        "No se puede eliminar: el postulante tiene certificaciones" to R.string.error_eliminar_postulante_certificaciones,
        "No se puede eliminar: el postulante tiene habilidades asignadas" to R.string.error_eliminar_postulante_habilidades,
        "No se puede eliminar: el postulante tiene redes sociales" to R.string.error_eliminar_postulante_redes,
        "No se puede eliminar: el tipo de documento tiene postulantes asociados" to R.string.error_eliminar_tipo_doc,
        "No se puede eliminar: el genero tiene postulantes asociados" to R.string.error_eliminar_genero,
        "No se puede eliminar: la red social tiene postulantes vinculados" to R.string.error_eliminar_red_social,
        "No se puede eliminar: la institucion tiene certificaciones asociadas" to R.string.error_eliminar_institucion_certificaciones,
        "No se puede eliminar: la institucion tiene ofertas academicas" to R.string.error_eliminar_institucion_ofertas,
        "No se puede eliminar: el grado academico tiene ofertas de trabajo" to R.string.error_eliminar_grado_ofertas,
        "No se puede eliminar: el grado academico tiene ofertas academicas" to R.string.error_eliminar_grado_ofertas_academicas,
        "No se puede eliminar: el grado academico tiene postulantes asociados" to R.string.error_eliminar_grado_postulantes,
        "No se puede eliminar: la empresa tiene ofertas de trabajo" to R.string.error_eliminar_empresa_ofertas,
        "No se puede eliminar: la empresa tiene experiencias laborales" to R.string.error_eliminar_empresa_experiencias,
        "No se puede eliminar: la oferta tiene requisitos asociados" to R.string.error_eliminar_oferta_requisitos,
        "No se puede eliminar: la oferta tiene postulaciones" to R.string.error_eliminar_oferta_postulaciones,
        "No se puede eliminar: la oferta academica tiene formaciones asociadas" to R.string.error_eliminar_oferta_academica,
        "No se puede eliminar: el tipo de certificacion tiene certificaciones asociadas" to R.string.error_eliminar_tipo_certificacion
    )

    fun translate(errorMessage: String?, context: Context? = null): String {
        if (errorMessage.isNullOrBlank()) return context?.getString(R.string.error_desconocido) ?: "Error desconocido"
        ERROR_MAP.entries.forEach { (key, resId) ->
            if (errorMessage.contains(key, ignoreCase = true)) {
                return context?.getString(resId) ?: errorMessage
            }
        }
        return errorMessage
    }
}
