package sv.ues.fia.eisi.bt.utils

object TriggerErrorTranslator {

    private val ERROR_MAP = mapOf(
        "UNIQUE constraint failed" to "Ya existe un registro con esos datos",
        "FOREIGN KEY constraint failed" to "No se puede modificar: tiene registros asociados. Elimine primero los registros dependientes",
        "NOT NULL constraint failed" to "Un campo obligatorio esta vacio",
        "constraint failed" to "Operacion no permitida por las reglas de validacion",
        "Duplicado: Ya existe un registro con esa clave" to "Ya existe un registro con esa combinacion de valores",
        "Ya existe un genero con ese nombre" to "Ya existe un genero con ese nombre",
        "Ya existe una categoria con ese nombre" to "Ya existe una categoria con ese nombre",
        "Ya existe un tipo de documento con ese nombre" to "Ya existe un tipo de documento con ese nombre",
        "Ya existe un departamento con ese nombre" to "Ya existe un departamento con ese nombre",
        "Ya existe un grado academico con ese nombre" to "Ya existe un grado academico con ese nombre",
        "Ya existe una red social con ese nombre" to "Ya existe una red social con ese nombre",
        "Ya existe una institucion con ese nombre" to "Ya existe una institucion con ese nombre",
        "Ya existe un municipio con ese nombre " to "Ya existe un municipio con ese nombre",
        "Ya existe un distrito con ese nombre en el municipio" to "Ya existe un distrito con ese nombre en el municipio",
        "Ya existe una habilidad con ese nombre" to "Ya existe una habilidad con ese nombre",
        "Ya existe una empresa con ese NIT" to "Ya existe una empresa con ese NIT",
        "Ya existe una empresa con ese nombre" to "Ya existe una empresa con ese nombre",
        "Ya existe un postulante con ese documento" to "Ya existe un postulante con ese documento",
        "Ya existe un postulante con ese email" to "Ya existe un postulante con ese email",
        "Ya existe un usuario con ese nombre" to "Ya existe un usuario con ese nombre",
        "Ya existe una oferta con ese titulo en la empresa" to "Ya existe una oferta con ese titulo en la empresa",
        "Ya existe un requisito con esa descripcion en la oferta" to "Ya existe un requisito con esa descripcion en la oferta",
        "Ya existe una experiencia con ese puesto para el postulante" to "Ya existe una experiencia con ese puesto para el postulante",
        "Ya existe una certificacion con ese codigo para el postulante" to "Ya existe una certificacion con ese codigo para el postulante",
        "El postulante ya aplico a esta oferta" to "El postulante ya aplico a esta oferta",
        "La oferta de trabajo ha vencido" to "La oferta de trabajo ha vencido",
        "El postulante debe tener un grado academico superior a Bachiller" to "El postulante debe tener un grado academico superior a Bachiller",
        "grado academico superior" to "El postulante debe tener un grado academico superior a Bachiller",
        "La red social ya esta vinculada al postulante" to "La red social ya esta vinculada al postulante",
        "La habilidad ya esta asignada al postulante" to "La habilidad ya esta asignada al postulante",
        "Ya existe una oferta academica para esa institucion y grado" to "Ya existe una oferta academica para esa institucion y grado",
        "Nivel academico insuficiente" to "No se permiten niveles de bachillerato o inferior",
        "nivel de bachillerato" to "No se permiten niveles de bachillerato o inferior",
        "Fecha inicio debe ser menor a fecha fin" to "La fecha de inicio debe ser anterior a la fecha de finalizacion",
        "fecha de inicio" to "La fecha de inicio debe ser anterior a la fecha de finalizacion",
        "Edad minima debe ser mayor o igual a 18" to "La edad minima debe ser mayor o igual a 18",
        "Edad minima no puede ser mayor a la maxima" to "La edad minima no puede ser mayor a la edad maxima",
        "edad minima" to "La edad minima debe ser mayor o igual a 18 y menor a la edad maxima",
        "La oferta ya caduco o fecha invalida" to "La fecha de caducidad debe ser posterior a la fecha de publicacion",
        "fecha de caducidad" to "La fecha de caducidad debe ser posterior a la fecha de publicacion",
        "El departamento asociado no existe" to "El departamento seleccionado no existe",
        "departamento" to "ya existe un registro con esa combinacion de valores",
        "El municipio asociado no existe" to "El municipio seleccionado no existe",
        "municipio" to "El municipio seleccionado no es valido",
        "La categoria asociada no existe" to "La categoria seleccionada no existe",
        "categoria" to "La categoria seleccionada no es valida",
        "El distrito asociado no existe" to "El distrito seleccionado no existe",
        "distrito" to "El distrito seleccionado no es valido",
        "El genero asociado no existe" to "El genero seleccionado no existe",
        "genero" to "El genero seleccionado no es valido",
        "El tipo de documento asociado no existe" to "El tipo de documento seleccionado no existe",
        "tipo de documento" to "El tipo de documento seleccionado no es valido",
        "Password minimo 8 caracteres" to "La contrasena debe tener al menos 8 caracteres",
        "contrasena" to "La contrasena debe tener al menos 8 caracteres",
        "Nivel de destreza debe ser 1, 2 o 3" to "El nivel de destreza debe ser 1 (Basico), 2 (Intermedio) o 3 (Avanzado)",
        "nivel de destreza" to "El nivel de destreza debe ser 1, 2 o 3",
        "postulante debe ser mayor de edad" to "El postulante debe ser mayor de 18 anos",
        "mayor de edad" to "El postulante debe ser mayor de 18 anos",
        "Correo electronico no valido" to "El formato del correo electronico no es valido",
        "correo electronico" to "El formato del correo electronico no es valido",
        "fecha de nacimiento" to "La fecha de nacimiento no es valida",
        "fecha de certificacion no puede ser menor a la fecha fin" to "La fecha de certificacion no puede ser menor a la fecha fin del periodo",
        "fecha de certificacion no puede exceder un año" to "La fecha de certificacion no puede exceder un año despues de la fecha fin del periodo",
        "fecha de certificacion no puede ser una fecha futura" to "La fecha de certificacion no puede ser una fecha futura",
        "fecha de obtencion no puede ser menor a la fecha fin" to "La fecha de obtencion no puede ser menor a la fecha fin del periodo",
        "fecha de obtencion no puede exceder un año" to "La fecha de obtencion no puede exceder un año despues de la fecha fin del periodo",
        "fecha de obtencion no puede ser una fecha futura" to "La fecha de obtencion no puede ser una fecha futura",
        "fecha inicio no puede ser una fecha futura" to "La fecha de inicio no puede ser una fecha futura",
        "fecha fin no puede ser una fecha futura" to "La fecha fin no puede ser una fecha futura",
        "No se puede eliminar: el departamento tiene municipios asociados" to "Elimine primero los municipios asociados a este departamento",
        "No se puede eliminar: el municipio tiene distritos asociados" to "Elimine primero los distritos asociados a este municipio",
        "No se puede eliminar: el distrito tiene postulantes asociados" to "Elimine primero los postulantes asociados a este distrito",
        "No se puede eliminar: el distrito tiene empresas asociadas" to "Elimine primero las empresas asociadas a este distrito",
        "No se puede eliminar: la categoria tiene habilidades asociadas" to "Elimine primero las habilidades asociadas a esta categoria",
        "No se puede eliminar: la habilidad esta asignada a postulantes" to "Elimine primero las relaciones de esta habilidad con postulantes",
        "No se puede eliminar: el postulante tiene postulaciones" to "Elimine primero las postulaciones de este postulante",
        "No se puede eliminar: el postulante tiene experiencias laborales" to "Elimine primero las experiencias laborales de este postulante",
        "No se puede eliminar: el postulante tiene formaciones academicas" to "Elimine primero las formaciones academicas de este postulante",
        "No se puede eliminar: el postulante tiene certificaciones" to "Elimine primero las certificaciones de este postulante",
        "No se puede eliminar: el postulante tiene habilidades asignadas" to "Elimine primero las habilidades asignadas a este postulante",
        "No se puede eliminar: el postulante tiene redes sociales" to "Elimine primero las redes sociales vinculadas a este postulante",
        "No se puede eliminar: el tipo de documento tiene postulantes asociados" to "Elimine primero los postulantes que usan este tipo de documento",
        "No se puede eliminar: el genero tiene postulantes asociados" to "Elimine primero los postulantes con este genero",
        "No se puede eliminar: la red social tiene postulantes vinculados" to "Elimine primero los postulantes vinculados a esta red social",
        "No se puede eliminar: la institucion tiene certificaciones asociadas" to "Elimine primero las certificaciones de esta institucion",
        "No se puede eliminar: la institucion tiene ofertas academicas" to "Elimine primero las ofertas academicas de esta institucion",
        "No se puede eliminar: el grado academico tiene ofertas de trabajo" to "Elimine primero las ofertas de trabajo con este grado academico",
        "No se puede eliminar: el grado academico tiene ofertas academicas" to "Elimine primero las ofertas academicas con este grado academico",
        "No se puede eliminar: el grado academico tiene postulantes asociados" to "Elimine primero los postulantes con este grado academico",
        "No se puede eliminar: la empresa tiene ofertas de trabajo" to "Elimine primero las ofertas de trabajo de esta empresa",
        "No se puede eliminar: la empresa tiene experiencias laborales" to "Elimine primero las experiencias laborales de esta empresa",
        "No se puede eliminar: la oferta tiene requisitos asociados" to "Elimine primero los requisitos de esta oferta de trabajo",
        "No se puede eliminar: la oferta tiene postulaciones" to "Elimine primero las postulaciones a esta oferta de trabajo",
        "No se puede eliminar: la oferta academica tiene formaciones asociadas" to "Elimine primero las formaciones academicas asociadas",
        "No se puede eliminar: el tipo de certificacion tiene certificaciones asociadas" to "Elimine primero las certificaciones con este tipo"
    )

    fun translate(errorMessage: String?): String {
        if (errorMessage.isNullOrBlank()) return "Error desconocido"
        ERROR_MAP.entries.forEach { (key, value) ->
            if (errorMessage.contains(key, ignoreCase = true)) {
                return value
            }
        }
        return errorMessage
    }
}
